### ISSUE TITLE
讲真，你们这个太难搞了

### ISSUE THREAD

**Issue by zuosc** [sjdy521/Mojo-Weixin#1]
环境太难搞。

教程又写的一笔带过

真是搞不动！！

**Comment by sjdy521** [comment]
linux上要编译安装，一提到编译我就怕，可能因为各种问题导致编译不过，这个文档里没办法体现
win上可能会更容易一些，环境都是打包好了，不涉及到编译，直接安装运行

**Comment by cnkedao** [comment]
centos6安装的话可参考
http://mp.weixin.qq.com/s?__biz=MzAwMTI3OTk3Nw==&mid=401775432&idx=1&sn=5659cedb3af819bda52b256d33dbc6cd#rd
