### ISSUE TITLE
下载下来的图片应为jpg

### ISSUE THREAD

**Issue by Xuanwo** [sjdy521/Mojo-Weixin#10]
我今天安装好之后进行试用，下载下来的二维码图片无法打开，提示`不是有效的png图片`，修改后缀名为`jpg`之后打开正常~

> PS: 感谢你的库，非常好用！

**Comment by sjdy521** [comment]
这个bug前天已经发现了，github已经修复 但还没同步到cpanm， 当前的解决方案：你可以在new的时候自定义二维码保存路径：


Mojo::Weixin->new(qrcode_path=>"/path/to/qrcode.jpg")


发自 网易邮箱大师
在2016年03月17日 20:20，漩涡 写道:

我今天安装好之后进行试用，下载下来的二维码图片无法打开，提示不是有效的png图片，修改后缀名为jpg之后打开正常~

**Comment by Xuanwo** [comment]
好的，非常感谢！
