### ISSUE TITLE
希望能够添加屏蔽或放行部分公众号消息的功能

### ISSUE THREAD

**Issue by xdujiang** [sjdy521/Mojo-Weixin#101]
加的公众号有些多，而且有些辣鸡公众号出于某种原因不便退掉，这样就使得推送很杂，但现在禁止推送公众号消息是一刀切，灵活度稍差，希望能添加类似Mojo-Weixin中allow_group和ban_group的功能，指定允许和拒绝推送的公众号。

**Comment by sjdy521** [comment]
OK 这个需求会考虑下 完成后在issue里通知你

**Comment by xdujiang** [comment]
谢谢~麻烦了

**Comment by sxml** [comment]
allow_group 和ban_group 感觉就那么别扭麻烦  allow_group允许A ban_group 要再有必禁止B?
我禁止群推送 一个个群号添加 好麻烦 不可以只允许A 其他就禁止?

**Comment by xdujiang** [comment]
@sxml 我没有试过，不过我猜一个是白名单一个是黑名单？如果是这样的话我觉得就挺有用的了。
你可以试试把ban注释掉只用allow那一项，也许能够符合你的要求？

**Comment by sjdy521** [comment]
allow就是白名单 
ban就是黑名单
仅此而已
