### ISSUE TITLE
连接微软小冰的时候，不会转发语言

### ISSUE THREAD

**Issue by tossp** [sjdy521/Mojo-Weixin#102]
转发出来是一个本地文件的地址

**Comment by sjdy521** [comment]
因为网页版本身不支持发送原生的语音消息 只能作为文件到形式转发 这个是官方的限制 没办法

**Comment by tossp** [comment]
我的意思是连文件都没发出来，，，就是一个字符串`(/tmp/xxxxxxxxxxxxx.mp3)`

**Comment by sjdy521** [comment]
是否有更新到最新版本？

**Comment by tossp** [comment]
是最新的版本

**Comment by sjdy521** [comment]
我找时间自己亲自测试下看看

**Comment by sjdy521** [comment]
时间较久，请升级到最新版试试，应该已经修复
