### ISSUE TITLE
用这个工具可以查看我已加入的群的成员信息吗？比如成员名称，微信id，简介等

### ISSUE THREAD

**Issue by rosstzc** [sjdy521/Mojo-Weixin#103]
如果不能查看，在这个工具的数据库会保存有以上提到的信息吗？  谢谢

**Comment by bollwarm** [comment]
可以，调用api就能查看相关信息

**Comment by rosstzc** [comment]
@bollwarm 微信官方的api应该不能读取 群成员的微信id吧？

**Comment by bollwarm** [comment]
https://github.com/sjdy521/Mojo-Weixin/blob/master/API.md#%E8%8E%B7%E5%8F%96%E7%BE%A4%E7%BB%84%E6%95%B0%E6%8D%AE

**Comment by bollwarm** [comment]
这是接口api说明
