### ISSUE TITLE
增加能调用系统命令并获取输出的插件Cmd.pm

### ISSUE THREAD

**Issue by yinflying** [sjdy521/Mojo-Weixin#104]
能够不断的使用插件才是使用这个工具的乐趣嘛，只是这个Mojo-Weixin的所有插件都是使用perl开发，这对于插件开发者来说，是一件很麻烦的事，比如说我，我就完全不懂perl，所以用perl做个能适用的插件太难受了。所以有了一个想法，即是做一个使用shell调用系统的命的插件，这样就可以实现插件功能的无限扩充，且不限任何语言。

由于本人不懂perl，就只能改改FuckDaShen.pm来写了一个最简单的插件脚本，实现上面功能。
```
package Mojo::Weixin::Plugin::Cmd;                                              
$Mojo::Weixin::Plugin::FuckDaShen::PRIORITY = 2;                                
                                                                                
sub call {                                                                      
    my $client = shift;                                                         
    my $callback = sub{                                                         
        my($client,$msg)=@_;                                                    
        return if not $msg->allow_plugin;                                                          
        return if $msg->content !~ /(^cmd\s.*)/;                                   
        my $key_word = $1;                                                         
        $key_word = substr($key_word,4); #去除cmd前缀                              
        $key_word =~ s/^\s*//g; #去除多余的空白                                    
        my $reply = `$key_word`; #调用系统执行命令并获取输出                       
        $client->reply_message($msg,$reply,sub{$_[1]->from("bot")}) if $reply;  
    };                                                                          
    $client->on(receive_message=>$callback,send_message=>$callback);            
};                                                                              
2;      
```
只需要在启动脚本中添加`$client-load("Cmd")即可启用。使用 “ cmd 命令内容” 获取相应的输出。
脚本简陃，并没有太多的测试，希望perl大神进一步完善。

**Comment by sjdy521** [comment]
这个项目最大的优势在于使用Openwx插件对外提供丰富的http api接口，使得开发者可以把项目视为黑盒子，通过api调用来接收或发送消息，使用任意其他语言进行二次开发，并实现自己的“插件”
所以 虽然提供了一个perl语言内部的插件编写框架，但实际上插件无非就是接收消息，根据需要再决定什么时候发送消息，完全可以无视自带的这些perl插件 用自己熟悉的编程语言通过api接口实现自己想要的功能（插件）

**Comment by yinflying** [comment]
原来如此， 可怜我这个IRC用户,也只能通过IRCshell这个插件来和IRC来互通了。不过话虽这样说，可是http_api也必须懂web的人才会使用，可能是面向另外一个项目的，这对个人用户来说，相当不友哇。
\me  懵了好久，看了好久api接口，才知道怎么修改插件。

**Comment by sjdy521** [comment]
并不需要了解web技术，只需要了解http协议即可，linux下有非常多可以http请求的命令，比如curl、wget等，在shell环境下用curl完全可以写shell脚本实现自己的发送接收消息处理，你也可以参考下demo里的sh脚本例子，强烈建议了解下http协议，毕竟这是当前整个互联网流行的基础

你提到的IRCshell是什么需求呢 没看懂 如果你并不是一个开发者 只是一个使用者 可以把你的原始需求详细描述一下 我可以帮你写一些perl代码的插件直接满足你的需要

**Comment by yinflying** [comment]
谢谢了哇，平时自己的用一些小插件而已，比如说查询IP，天气，或者做翻译之类，或者用于查询机器的状态之类的。这类小插件功能需求毕竟是是无穷尽的，最重要的是具有时效性，让您来写和维护个人觉得浪费精力过多。实际上，我倒是觉得把我上面的cmd插件完善一下，倒是一件很有价值的事情，如权限控制之类（毕竟别人也能使用你的终端来发送命令是一件很危险的事)。至于该怎么用，交给用户就好了。
