### ISSUE TITLE
用docker起的服务 可以接收消息和用户信息，但是没法发送消息

### ISSUE THREAD

**Issue by byYufeng** [sjdy521/Mojo-Weixin#111]
rt

**Comment by sjdy521** [comment]
docker镜像肯定是可以发生消息的 问题描述不够具体 可以再详细描述下情况

**Comment by byYufeng** [comment]
用docker run -it ...启动容器之后，扫码登录就开始占用控制台持续滚动的接收消息
另开了一个窗口使用 curl http://127.0.0.1:3000/openwx/send_friend_message?id=123&content=456发送消息 
过一段时候后响应 Empty reply from server 
qq和微信都是这个情况

**Comment by sjdy521** [comment]
curl命令的url地址有没有加引号？

**Comment by byYufeng** [comment]
是这个问题 后来也发现了

**Comment by MiLeskylimit** [comment]
麻烦问下，这个id是指的微信号吗？
