### ISSUE TITLE
莫明「收到无法识别消息，已将其忽略」

### ISSUE THREAD

**Issue by geeyan** [sjdy521/Mojo-Weixin#114]
再次遇到了，已登录微信号在服务器上不能正常接收和发送消息了。
解决办法是：把登录微信号在手机上打开一下，服务器端就正常了。

![image](https://cloud.githubusercontent.com/assets/4083759/25813400/f65e5254-344b-11e7-9c32-ad7453cb744f.png)

这个有没有更自动化的办法处理呢？

**Comment by sjdy521** [comment]
这个可能程序登录微信之后长时间没有活动，服务端就返回了一些异常的消息，通常情况下重新登录扫码就可以解决这个问题，可以考虑出现这种情况时，让程序自动重新登录，或者其他形式想办法通知到主人

**Comment by geeyan** [comment]
这里可以把码给输出到日志，这样方便观察后续继续优化 @sjdy521

**Comment by sjdy521** [comment]
好主意 我会加上

**Comment by sjdy521** [comment]
@geeyan 
建议已经支持，参考如下commit： https://github.com/sjdy521/Mojo-Weixin/commit/ba8c9878320f4381388ba0f79fb3a5dc91f6e4d6

> 对于接收消息中无法识别的消息代码，打印日志中增加具体的代码值，日志打印形式：
> "收到无法识别消息代码[3]，已将其忽略"
> 
> 同时，客户端会触发 unknown_retcode 事件，方便做自定义处理
> $client->on(unknown_retcode=>sub{
>     my ($client,$retcode) = @_;
>     ...;
> });
