### ISSUE TITLE
图片发送过多会出现图片发送不了的情况

### ISSUE THREAD

**Issue by 0x14os** [sjdy521/Mojo-Weixin#116]
通过API发送消息 返回的json中显示成功， 但是实际上并没有发送成功。

测试情况下：1分钟发一条图片消息， 大概持续3，4个小时后出现图片发送失败的情况。请问怎么排查问题？ 或者有更详细的日志？

**Comment by 0x14os** [comment]
debug级别的日志:
[weixin_client_01][8197][17/05/13 18:05:34] [debug] 插件[Mojo::Weixin::Plugin::Openwx]发送消息[1494669933967]上报成功
[weixin_client_01][8197][17/05/13 18:05:37] [debug] 正在上传媒体[https://ww2.sinaimg.cn/large/006tNc79gy1ffhdzp97k2j30m80m8q6s.jpg]，当前进度:1/1
[weixin_client_01][8197][17/05/13 18:05:37] [debug] 消息[ 1494669933967 ]发送失 败，尝试重新发送，当前TTL: 4
[weixin_client_01][8197][17/05/13 18:05:39] [debug] 消息[ 1494669933967 ]发送失 败，尝试重新发送，当前TTL: 3
[weixin_client_01][8197][17/05/13 18:05:43] [debug] 消息[ 1494669933967 ]发送失 败，尝试重新发送，当前TTL: 2
[weixin_client_01][8197][17/05/13 18:05:45] [debug] 消息[ 1494669933967 ]发送失 败，尝试重新发送，当前TTL: 1
[weixin_client_01][8197][17/05/13 18:05:48] [群消息] 我->搞笑图片分享群 : [图片](https://ww2.sinaimg.cn/large/006tNc79gy1ffhdzp97k2j30m80m8q6s.jpg)[发送失 败(unknown error)]
[weixin_client_01][8197][17/05/13 18:05:48] [debug] 插件[Mojo::Weixin::Plugin::Openwx]发送消息[1494669933967]上报成功

**Comment by 0x14os** [comment]
希望作者能提供帮助， 感谢。 愿意付费~

**Comment by sjdy521** [comment]
发送失败的原因是 unknown error 这个从日志看不出来原因，无法提供具体的帮助
可以在new里加一个 Mojo::Weixin->new(http_debug=>1,log_path=>"debug.log") 把底层http请求产生的debug.log也发给我一下
这样才能够彻底找出来发送失败的原因

也有看可能发送图片过于频繁被腾讯给限制了，这种情况就没办法了

**Comment by lijibiao** [comment]
也经常碰到这种问题，基本上都是腾讯限制了

**Comment by sjdy521** [comment]
腾讯好像有每天发送图片数量限制 可能每天80张
