### ISSUE TITLE
IRC显示图片

### ISSUE THREAD

**Issue by wtry** [sjdy521/Mojo-Weixin#117]
如果IRC显示图片，只是需要一个url路径的话，又没有可能直接返回一个本地的http://127.0.0.1/的路径？

**Comment by sjdy521** [comment]
当前的解决方案是把图片上传到第三方图床，显示成一个在线的url

IRCShell模块参数说明： https://metacpan.org/pod/distribution/Mojo-Weixin/doc/Weixin.pod#Mojo::Weixin::Plugin::IRCShell

```
$client->load("IRCShell",data=>{
    master_irc_nick => "xxxx",
    upload_api => "http://img.vim-cn.com/"; #图床api地址，将图片转为连接，方便在irc上查看图片
                    #支持兼容 http://img.vim-cn.com/ 的接口，考虑到隐私问题，默认不开启
});
```

**Comment by lilydjwg** [comment]
建议使用 https 哟。自己搭建也很容易的，项目在 https://github.com/Vim-cn/elimage
