### ISSUE TITLE
是否可保留原始数据，而不做「未知表情」的转换？

### ISSUE THREAD

**Issue by geeyan** [sjdy521/Mojo-Weixin#118]
原始名称/字符串是否可以加个参数来控制不转换？有一些场景需要用到原始的emoji表情 😂
![image](https://cloud.githubusercontent.com/assets/4083759/26308881/9d0fc3e4-3f2d-11e7-8f81-bdb59ed90ed6.png)

https://github.com/sjdy521/Mojo-Weixin/blob/78b5b46c32c8ce84651d06ef338848041772802d/lib/Mojo/Weixin/Util.pm#L15

**Comment by sjdy521** [comment]
当前已经支持这种参数
Mojo::Weixin->new(emoji_to_text=>0) # 在对象初始化的new方法中设置emoji_to_text => 0

参考开发文档：
https://metacpan.org/pod/distribution/Mojo-Weixin/doc/Weixin.pod#new-%E5%88%9D%E5%A7%8B%E5%8C%96%E4%B8%80%E4%B8%AA%E5%BE%AE%E4%BF%A1%E5%AE%A2%E6%88%B7%E7%AB%AF%E5%AF%B9%E8%B1%A1

**Comment by geeyan** [comment]
好的，thx!!
