### ISSUE TITLE
http请求阻塞

### ISSUE THREAD

**Issue by vD1S** [sjdy521/Mojo-Weixin#119]
请问下，Openwx模块如何修改为非阻塞http请求

**Comment by vD1S** [comment]
如何异步执行啊
![qq 20170606162828](https://cloud.githubusercontent.com/assets/26621506/26820443/6750ae40-4ad5-11e7-8a79-05c44fe82704.jpg)

**Comment by sjdy521** [comment]
github最新代码已经支持
发送消息添加参数aysnc=1即可
