### ISSUE TITLE
微信群中的name和displayname有何区别？

### ISSUE THREAD

**Issue by Xuanwo** [sjdy521/Mojo-Weixin#12]
RT，此外微信群的ID保证不变么？

**Comment by sjdy521** [comment]
@Xuanwo 
本地登录期间（也就是你下次扫描二维码重新登录之前）微信群的id是不变的，重新扫描二维码登录群的id可能会发生变化

`name`属性就是手机微信里的【群聊名称】，但你会发现你随便拉张三、李四建一个群聊，【群聊名称】通常显示为“未命名”，也就是空的

而你手机上看到的群名称通常会叫做 `张三、李四...`（也就是所谓的`displayname`）

直到你重新设置了群聊名称，`name`属性才会变成你设置的

简而言之，`displayname`就是你手机上显示的群聊名称，`name`是手动设置的群聊名称，如果没有设置就为空

**Comment by Xuanwo** [comment]
@sjdy521 非常感谢，那你文档中此处是不是有些问题？
https://github.com/sjdy521/Mojo-Weixin/blame/master/API.md#L159

这个Markname是就是指displayname么？我不管用name还是displayname都没有发送成功，id+content是可以的。

**Comment by sjdy521** [comment]
微信群没有markname属性，我的文档有错误，可以用displayname来发消息
`/openwx/send_group_message?displayname=xxx&content=xxx`
文档错误我已修复

**Comment by Xuanwo** [comment]
@sjdy521 Very nice！
我回去再研究研究，叨扰啦。

**Comment by sjdy521** [comment]
有什么问题随时欢迎，也可以加群交流

**Comment by Xuanwo** [comment]
OK
