### ISSUE TITLE
单独获取微信群列表API

### ISSUE THREAD

**Issue by timosss** [sjdy521/Mojo-Weixin#123]
现在的获取群列表API，包涵了群所有信息，在有大量群的情况下，调用此API会很慢。建议把群列表和群成员单独分开来调用！

**Comment by sjdy521** [comment]
收到，会提供一个单独的api，或者在已有的api上增加一个控制参数，只返回不包含群成员的信息

**Comment by sjdy521** [comment]
Openwx插件已经增加了对应的接口`/openwx/get_group_basic_info`返回群列表信息（不包含群成员）
