### ISSUE TITLE
增加撤回消息功能

### ISSUE THREAD

**Issue by cntlis** [sjdy521/Mojo-Weixin#126]
网页版微信目前已经有撤回消息的功能了，能不能把这个功能也给加上啊，
接口地址是https://wx2.qq.com/cgi-bin/mmwebwx-bin/webwxrevokemsg
接口的提交参数为
{"BaseRequest":{"Uin":1982671425,"Sid":"pAy46+aZBfaqKEcE","Skey":"@crypt_9ee9c9b6_fa28baef4dc353b3ec0bcb63b8d6af70","DeviceID":"e268833895794456"},"SvrMsgId":"5504110410557500928","ToUserName":"@756d6da21cf71c6b32e47ea151dfc8d1","ClientMsgId":"15012412489260924"}
其中SvrMsgId为推送接口返回的MsgId，ClientMsgId为系统返回的ClientMsgId

**Comment by vD1S** [comment]
的确有这个需求 。

**Comment by sjdy521** [comment]
github最新代码已经支持
