### ISSUE TITLE
隔一段时间就会出现， 导致退出

### ISSUE THREAD

**Issue by epiphyllum** [sjdy521/Mojo-Weixin#131]
https://webpush.wx2.qq.com/cgi-bin/mmwebwx-bin/synccheck?r=1503114943506&skey=%40crypt_cd126a53_d4dfa0d6965932f586a5781253253458&sid=O2vMKAv8at2SUuKV&uin=1688597105&deviceid=e895859469778014&synckey=1_675751270%7C2_675751521%7C3_675751449%7C11_675751395%7C13_675710019%7C201_1503114656%7C1000_1503111809%7C1001_1503105332%7C1002_1503037832&_=1503114943506 请求失败: - Request timeout

**Comment by epiphyllum** [comment]
<img width="1430" alt="k" src="https://user-images.githubusercontent.com/8348065/29485261-75dd588a-8501-11e7-83d9-d41be8bc624a.png">

**Comment by vD1S** [comment]
同意遇到过这个提示，只是没有退出。

**Comment by sjdy521** [comment]
可以不用管 没太大影响 只是个警告
