### ISSUE TITLE
定期删除缓存文件

### ISSUE THREAD

**Issue by cntlis** [sjdy521/Mojo-Weixin#132]
新增一个图片视频缓存目录和Session目录分开，然后缓存目录可以按照日期分割开，并且可以定期删除的功能

**Comment by yEs1do** [comment]
你所说的是不是这个意思：
https://metacpan.org/pod/distribution/Mojo-Weixin/doc/Weixin.pod#new
（new中参数tmpdir与media_dir部分）
https://metacpan.org/pod/distribution/Mojo-Weixin/doc/Weixin.pod#Mojo::Weixin::Plugin::ImageStore
（ImageStore插件功能）

定期删除我不知道怎么实现

**Comment by cntlis** [comment]
嗯嗯，谢谢哇
