### ISSUE TITLE
提个关于登陆方面的小建议

### ISSUE THREAD

**Issue by dozaza** [sjdy521/Mojo-Weixin#133]
想提个关于登陆方面的功能上的建议。

因为平时会电脑上登陆的，所以一点电脑端登陆，就会把服务器端的给踢掉了（万恶的微信单点登陆）。

然后一旦电脑不用了，想要切回手机，就要自己登陆到服务器重启下service，感觉有点麻烦。

不知道是否有可能通过手机，来发送一个消息或者什么的，给服务器重新来个登陆请求？

**Comment by sjdy521** [comment]
服务端微信掉线后就无法再接收到手机发送的消息，所以也没办法感知到手机发送的消息
可以自己研究下如何远程控制server来启动某个程序，这方面我没什么经验
以前我都是手机安装个ssh的客户端，需要的时候就ssh远程连接到服务器，然后执行命令
只是手机屏幕比较小，这样操作比较的累
