### ISSUE TITLE
Does the images in /tmp got auto-deleted?

### ISSUE THREAD

**Issue by Turgon-Aran-Gondolin** [sjdy521/Mojo-Weixin#134]
Does the downloaded images in /tmp got auto-deleted after a while? If so, is there a way to prevent it?

**Comment by sjdy521** [comment]
Things in '/tmp' will be deleted by OS, it's not persistent.
You can set your own dir by following:
```Mojo::Weixin->new(media_dir=>"/your/owner/path");```
