### ISSUE TITLE
关于微信协议接口的问题

### ISSUE THREAD

**Issue by sgon00** [sjdy521/Mojo-Weixin#136]
弱弱的问一句，微信协议接口是如何获得的？这是自己摸索出来的 （通过wireshark)？还是微信开放了自己个人聊天的接口？我在 https://open.weixin.qq.com/ 没有找到呀？如果有开放的接口和文档，能帮忙给个链接吗？谢谢您了。我今天才知道有这么多开源的微信聊天客户端，我一直以为是无法实现的，真是孤落寡闻了。。。

**Comment by yixtan** [comment]
你孤陋寡闻了

**Comment by sgon00** [comment]
@yixtan 谢谢您的回复，我知道我孤陋寡闻了。我是非常非常的孤陋寡闻！之前我自己在提问的时候就已经承认了。但您是否可以回答我的问题？谢谢您。

**Comment by yixtan** [comment]
是非公开的私有接口，所以悠着点用。

**Comment by sgon00** [comment]
@yixtan 非公开的私有接口？哪里有文档吗？中英文都可以，非常感谢！全英语没有问题。PS：这是怎么总结出来的？tcpdump出来的？谢谢您。

**Comment by bollwarm** [comment]
通过抓web交互下，无非html和js ，对用户来说都是透明的

**Comment by sjdy521** [comment]
没有那么高深，谈不上孤陋寡闻，思路也很简单，就是通过程序去尽量模拟浏览器的行为，把浏览器上网页可以实现的操作自动化掉而已，接口全部都来自浏览器抓包，按F12即可，不需要wireshark，抓包看不懂的地方也可以直接浏览器里看html和javascipt源码，所以相对简单，网上这种来源的分享才会很多

**Comment by sgon00** [comment]
@bollwarm 感谢您的回复。
@sjdy521 非常感谢作者您的详细回复。没想到现在还有人坚持使用perl的，您真是太牛了！perl是我大学期间最喜欢的语言，也是曾经最擅长的语言。不过因为太小众了，后来毕业后，就没再使用。听说科学家和做数据统计的行业用的比较多。这是些体外话，言归正传，现在我明白这些接口的来源了，您说网上这种分享有很多，您有没有推荐的写的比较好的文档或网站呢？如果没有的话，那我就多学习下您的接口了。^_^ 谢谢。

**Comment by sjdy521** [comment]
因为写这些分享的人很多我就懒得写了，可以参考我github项目README结尾收录的几个友情链接的项目，很多都有整理类似的分享
