### ISSUE TITLE
In IRC client sendFile prefix can only recognize normal filename

### ISSUE THREAD

**Issue by Turgon-Aran-Gondolin** [sjdy521/Mojo-Weixin#137]
As what I said, by "normal" I mean anything but those that need `\` or quote the whole part for it to work. 
i.e something like this `sendFile /tmp/a\ b` won't work but `sendFile /tmp/ab` can.

**Comment by sjdy521** [comment]
bug already fixed with the latest github commit.
You don't need to escape space character with slash `\`.
instead of that  , you can do like this:

` sendFile "/tmp/a b" `
or
`sendFile '/tmp/a\ b'`

**Comment by Turgon-Aran-Gondolin** [comment]
OK, thanks very much.
