### ISSUE TITLE
Feature request: 为微信好友添加标签，拉入指定群组

### ISSUE THREAD

**Issue by Xuanwo** [sjdy521/Mojo-Weixin#14]
- [ ] 可以为指定的好友添加相关标签
- [ ] 将好友拉入指定群组

**Comment by sjdy521** [comment]
1）网页版不支持给好友添加相关标签，所以这个需求满足不了，只能手机上添加标签（程序自动同步）
2）把好友拉到指定的群组 这个可以支持，我近期会实现一下

**Comment by sjdy521** [comment]
@Xuanwo 
`将好友拉入指定群组` 需求已经实现，参见 [API文档](API.md) 中关于
/openwx/create_group
/openwx/invite_friend
