### ISSUE TITLE
增加微信红包提醒模块

### ISSUE THREAD

**Issue by Rstatistics** [sjdy521/Mojo-Weixin#141]
大佬，能否增加微信红包提醒啊。嘿嘿

**Comment by sjdy521** [comment]
基于网页微信 不支持红包

**Comment by Rstatistics** [comment]
my $object = $msg->type eq "group_notice"?$msg->group:$msg->sender;
if($msg->content =~ /收到红包，请在手机上查看/){
my $sender = $msg->type eq "friend_message"?$object->displayname:$object->displayname;
$luck->send("$sender：红包");
$object->stick(1);#谁发红包就置顶谁

**Comment by sjdy521** [comment]
👍👍👍

**Comment by Rstatistics** [comment]
不知道您想加这个功能否？想加的话，麻烦大佬优化一下。谢谢灰总啦。
[GoodLuck.zip](https://github.com/sjdy521/Mojo-Weixin/files/1456216/GoodLuck.zip)
$client->load("GoodLuck",data=>{
    is_need_at  => 0,                 #可选，是否需要艾特我来触发智能回复
    comamnd_on  => "启动",            #可选，启动智能回复的命令，在手机端发送给任何人/群该消息内容即可
    comamnd_off => "停止",            #可选，停止智能回复的命令，在手机端发送给任何人/群该消息内容即可
    allow_group        => [""],       #可选，允许插件的群显示名称
    ban_group          => ["私人群"], #可选，禁用该插件的群显示名称
    allow_group_member => [""],       #可选，允许该插件的群成员显示名称
    ban_group_member   => [""],       #可选，禁用该插件的群成员显示名称
    ban_friend         => ["坏蛋"],   #可选，禁用该插件的好友显示名称
    allow_group_reply  => 1,          #可选，是否允许回复群消息，默认1
    allow_friend_reply => 1,          #可选，是否允许回复好友消息，默认1
});

**Comment by sjdy521** [comment]
可以直接给我提PR
