### ISSUE TITLE
请问大佬用的什么工具捕获微信的消息的？

### ISSUE THREAD

**Issue by Rstatistics** [sjdy521/Mojo-Weixin#142]
灰灰大佬，我想捕获微信的转账信息，可是，网页版的微信能收到转账提醒按钮，就是没有文字提示，我发现它不是group_info，真心不知道它是什么类型的信息，没办法捕获啊。所以请教大佬，您是用什么工具来研究网页版微信滴？谢谢！

**Comment by sjdy521** [comment]
抓包只需要chrome浏览器按F12就可以

转账的消息没有去研究过，应该也是在sync接收消息的api中返回

**Comment by sjdy521** [comment]
转账消息已支持
