### ISSUE TITLE
如何接收转账和红包消息呢？

### ISSUE THREAD

**Issue by dadiyang** [sjdy521/Mojo-Weixin#144]
在wxpy中收到转账和红包消息会以类别NOTE的消息接收。在咱们这里，我看了说明和文档，也自己测试了转账和红包，但是都没有上报任何消息。Mojo-Weixin这里是否支持这些信息的上报呢？没有的话，什么时候可以加上来呢？

[http://wxpy.readthedocs.io/zh/latest/messages.html#id2](url)

**Comment by sjdy521** [comment]
当前不支持此类消息，感谢提供的PR，我会尽快合并到主分支

**Comment by sjdy521** [comment]
已支持
