### ISSUE TITLE
扫码登录出错不提醒。

### ISSUE THREAD

**Issue by dadiyang** [sjdy521/Mojo-Weixin#146]
扫码完成后有时候会出现登录不了的情况。返回数据为：
[rs.txt](https://github.com/sjdy521/Mojo-Weixin/files/1484472/rs.txt)

希望出现这种情况的时候API能够上报事件予以提示。

<error><ret>1203</ret><message>为了你的帐号安全，此微信号已不允许登录网页微信。你可以使用Windows微信或Mac微信在电脑端登录。Windows微信下载地址：https://pc.weixin.qq.com  Mac微信下载地址：https://mac.weixin.qq.com</message></error>

**Comment by sjdy521** [comment]
程序运行过程中打印的日志发来看看？
