### ISSUE TITLE
建议将Message中图片，视频，文件等下载到文件夹中

### ISSUE THREAD

**Issue by demostars** [sjdy521/Mojo-Weixin#147]
首先感谢作者对项目的付出，很棒的项目。

一个小小的反馈，建议将收到和发送的文件，图片等下载到文件夹中，而不是根目录。如果可以的话，能够根据微信号区分也是极好的，对多账号区分有利。

反馈如上，感谢~

**Comment by bollwarm** [comment]
你可以自己配置的

**Comment by demostars** [comment]
@bollwarm 
请问在那边配置呢，我是用的 https://github.com/sjdy521/Mojo-StrawberryPerl ，还没仔细看wiki，wiki中有说明么~

**Comment by bollwarm** [comment]
启动项目配个

media_dir=>"media",

这个media是就是那些的目录

**Comment by sjdy521** [comment]
Mojo::Weixin->new(media_dir=>"xxxx")

**Comment by chernglee** [comment]
视频文件是空的，并不会自动下载，能否自动点击让它接收？
