### ISSUE TITLE
How long a session can last?

### ISSUE THREAD

**Issue by suntong** [sjdy521/Mojo-Weixin#148]
Hi, 

If I install `Mojo-Weixin`, and start the [echo-reply](https://github.com/sjdy521/Mojo-Weixin/blob/master/demo/echo-reply.pl), how long the session can last? I.e., if I leave it running on a reliable server, how soon will it stop responding? 

I ask because the other framework/platform that I tried can only last for a very very short time, while I was hoping it could go on for months. 

Thx

**Comment by bollwarm** [comment]
Mojo_weixin can holde on about a month，but there are two  requirements one your account  of mobile can‘t offline and  have not messages  interactive for a long times

**Comment by suntong** [comment]
Oh, Gotya. Thx a lot!

**Comment by suntong** [comment]
Just want to confirm, both requirements are actually the restrain from Weixin, not limitation of Mojo_weixin itself, right?

**Comment by sjdy521** [comment]
"both requirements are actually the restrain from Weixin, not limitation of Mojo_weixin itself, right" 
---> the answer is YES
