### ISSUE TITLE
二维码在哪里获得？

### ISSUE THREAD

**Issue by SparrowRick** [sjdy521/Mojo-Weixin#149]
二维码显示已保持到本地后要怎样才可以查看二维码？？

**Comment by sjdy521** [comment]
二维码只是一个图片文件，如何查看一个图片文件，这个应该不难吧…

**Comment by SparrowRick** [comment]
好了！我弄好了，但是在使用screen命令让他一直在后台运行时遇到了困难。。具体命令怎么用啊

2018年1月14日 15:47，"sjdy521" <notifications@github.com>写道：

二维码只是一个图片文件，如何查看一个图片文件，这个应该不难吧…

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/sjdy521/Mojo-Weixin/issues/149#issuecomment-357494456>,
or mute the thread

**Comment by sjdy521** [comment]
screen我没用过 我都是用nohup命令 你可以百度下linux系统如何后台运行程序 方法很多

**Comment by SparrowRick** [comment]
好滴！多谢你！我解决了！Screen -R新建一个窗口就好了

2018年1月14日 21:39，"sjdy521" <notifications@github.com>写道：
