### ISSUE TITLE
功能请求：支持好友管理

### ISSUE THREAD

**Issue by Xuanwo** [sjdy521/Mojo-Weixin#15]
Openwx 支持如下好友管理功能：

- [x] 添加好友 （不需要主动添加，只需要在别人加你的时候点击添加即可，网页版应该有这个功能）
- [ ] 删除好友
- [x] 为好友添加标签

**Comment by Xuanwo** [comment]
![2016-04-29 2 58 30](https://cloud.githubusercontent.com/assets/5351546/14909918/4f0160de-0e1b-11e6-9037-f502de2c7976.png)

供你参考：
这个人已经添加我为好友，但是我还没有加他。我只需要点击右边那个加号就可以把他添加为我的好友。

**Comment by sjdy521** [comment]
【添加好友 】这个需要专门构造测试环境来抓包，会再找时间完成
 【删除好友】web微信似乎不支持
【 为好友添加标签】已经完成支持
新增两个api接口：
/openwx/set_group_displayname 用于设置群组的显示名称
/openwx/set_friend_markname 用于设置好友的备注（标签）名称
详细用法见API文档

**Comment by sjdy521** [comment]
【添加好友 】功能已经支持
/openwx/make_friend

**Comment by sjdy521** [comment]
>添加好友 （不需要主动添加，只需要在别人加你的时候点击添加即可，网页版应该有这个功能）

已经支持，参见 [AutoVerify](https://metacpan.org/pod/distribution/Mojo-Weixin/lib/Mojo/Weixin.pod#Mojo::Weixin::Plugin::AutoVerify) 插件

**Comment by Xuanwo** [comment]
Cool

**Comment by changwu** [comment]
make_friend 接口是不是已经失效啦？试了几次都不行。
