### ISSUE TITLE
获取不到用户登录失败的事件

### ISSUE THREAD

**Issue by dadiyang** [sjdy521/Mojo-Weixin#150]
不知道从什么时候开始，新的微信号已经不支持网页版登录，所以用接口调用登录的时候会出错。
咱们这个项目很好用，但在遇到这种登录不了的情况时并没有一个事件上报，而且直接重试了。

```
<error><ret>1203</ret><message>为了你的帐号安全，此微信号已不允许登录网页微信。你可以使用Windows微信或Mac微信在电脑端登录。Windows微信下载地址：https://pc.weixin.qq.com  Mac微信下载地址：https://mac.weixin.qq.com</message></error>
登录结果异常，再次尝试
```

下面是运行日志：
![image](https://user-images.githubusercontent.com/28141217/35907124-ef326df8-0c27-11e8-995e-7e6d9f55f6c4.png)

希望可以将这个事件上报，让调用方知道发生了什么事情。
谢谢！

**Comment by sjdy521** [comment]
收到 我近期添加一下

**Comment by sjdy521** [comment]
github最新代码已经支持
参见 [login事件参数说明](https://github.com/sjdy521/Mojo-Weixin/blob/master/API.md#%E5%85%B6%E4%BB%96%E9%9D%9E%E6%B6%88%E6%81%AF%E7%B1%BB%E4%BA%8B%E4%BB%B6%E4%B8%8A%E6%8A%A5)
