### ISSUE TITLE
能否用 pickle 持久化 登录信息呢?

### ISSUE THREAD

**Issue by yssource** [sjdy521/Mojo-Weixin#154]
喜欢用 `Mojo-Weixin`, 和 其他的脚本做客户端, 比如 [itchat](https://github.com/littlecodersh/ItChat). [wechatircd](https://github.com/MaskRay/wechatircd)
- 如果同时使用他们时, 不同的客户端同时用不同的登入方法扫描二维码, 我担心会强制下线其中一个.
- 如果能够两个客户端并行登入使用的话, 能否考虑一下, 用 `pickle` 持久化登录信息.

pickle 的概念, 举例如下
```perl

use Python::Serialise::Pickle qw( );

# Work around P::S::Pickle 0.01's extremely limiting interface.
sub pickle_dumps {
   open(my $fh, '>', \my $s) or die $!;
   my $pickle = bless({ _fh => $fh }, 'Python::Serialise::Pickle');
   $pickle->dump($_[0]);
   $pickle->close();
   return $s;
}

my $data = [ "somestring.data", [ 178346464, 1234568 ] ];
my $message = pack("N/a*", pickle_dumps($data));
```

**Comment by NeverMin** [comment]
> 如果同时使用他们时, 不同的客户端同时用不同的登入方法扫描二维码, 我担心会强制下线其中一个.
很确定会把另外一个踢下线, 我相信限制是由于微信.

**Comment by yssource** [comment]
嗯, 我也觉得会踢下线.
对 perl 不是很熟, 不知 `pickle` 持久化是否对 Mojo-Weixin 有借鉴意义? 
没有啥意义的话, 请作者关掉这个issue.

**Comment by sjdy521** [comment]
相同账号不允许多处登录，这个是微信服务端控制的，登录信息本地化并不能解决这个问题
另外，Mojo-Weixin当然的客户端登录运行状态（主要是cookie）一直都有序列化到本地，目的是为了程序短时间重新运行的时候，能够自动加载上一次登录状态，免扫码登录，这个和浏览器的缓存是相似的机制，仅能发挥这样的作用
