### ISSUE TITLE
会被微信封号吗?

### ISSUE THREAD

**Issue by suntong** [sjdy521/Mojo-Weixin#156]
在 https://github.com/sjdy521/Mojo-Weixin/issues/125 里面有说，

> 过一段时间再尝试下看看有没有恢复，据说已经恢复了

我用其他软件被封号了，一直都没有恢复。现在更是看到如下消息：

![image](https://user-images.githubusercontent.com/30145089/38874936-e14209f2-428b-11e8-9fca-794ec59d8fb5.jpg)

所以想问一下，Mojo-Weixin 底层用的是微信网页版技术，还是微信API? 

谢谢

**Comment by dadiyang** [comment]
Mojo-Weixin用的是微信网页版。

**Comment by suntong** [comment]
Thanks @dadiyang for the kind response.
