### ISSUE TITLE
希望给Openwx插件添加跨域配置

### ISSUE THREAD

**Issue by dadiyang** [sjdy521/Mojo-Weixin#158]
最近在学一些前端的东西，一直觉得Mojo-Weixin这个项目特别好，所以想开发并开源一个前端的项目。
但遇到了跨域的问题。我可以通过JavaWeb封装一下，处理跨域的Websocket的问题。但是那样会增加一些复杂度，所以想问一下，咱们项目中能否支持一下跨域和Websocket。

![image](https://user-images.githubusercontent.com/28141217/39474615-6b2f1082-4d87-11e8-9294-297c362e1668.png)

例如在java中可以对配置中的ALLOW_ORIGINS中的所有来源添加允许跨域的头信息。
![image](https://user-images.githubusercontent.com/28141217/39474823-58ca775a-4d88-11e8-988a-cb24fd2284a2.png)

**Comment by bollwarm** [comment]
这个跟跨域没关系好不好，目前接口是没有任何限制的的，但是你监听的到localhost的话，只有本机能访问，这是最基本的常识呀，怎么扯到跨域去了

**Comment by sjdy521** [comment]
@bollwarm 如果web页面的域名和api接口域名不属于同一个域，这个还是需要跨域相关的配置的
@dadiyang 当前Openwx只有一个“Access-Control-Allow-Origin: *” 来支持跨域，还缺少了其他你截图中包含的header，这个我都给加上一下

**Comment by sjdy521** [comment]
已支持更多跨域的请求方法（OPTIONS、HEAD）和header

**Comment by sjdy521** [comment]
希望能分享出来

**Comment by dadiyang** [comment]
嗯嗯。会的。

**Comment by dadiyang** [comment]
兑现承诺哈。这两个做出来了，前后端配合使用。由于时间关系，使用文档还没有写。后面再慢慢补上。
微信前端项目：[vue-wechat-fe](https://github.com/dadiyang/vue-wechat-fe)
微信后端封装项目：[java-wechat-be](https://github.com/dadiyang/java-wechat-be)

**Comment by sjdy521** [comment]
@dadiyang 感谢分享 我找时间学习下你这个项目

**Comment by dadiyang** [comment]
> 兑现承诺哈。这两个做出来了，前后端配合使用。由于时间关系，使用文档还没有写。后面再慢慢补上。
> 微信前端项目：[vue-wechat-fe](https://github.com/dadiyang/vue-wechat-fe)
> 微信后端封装项目：[java-wechat-be](https://github.com/dadiyang/java-wechat-be)

半年前写这两个项目的时候技术还太菜，实现得太差。已删除。
后续有时间我会基于 https://github.com/dadiyang/vue-wechat 这个项目再做一个。
