### ISSUE TITLE
这个只能用来登录个人微信号是不是？

### ISSUE THREAD

**Issue by harryhare** [sjdy521/Mojo-Weixin#161]
rt

**Comment by NeverMin** [comment]
是的, 你想登录公众号?

Philip Jay Fry <notifications@github.com> 于2018年5月28日周一 下午5:04写道：

**Comment by harryhare** [comment]
公众号收发消息是不是走wx提供的API就可以了？

**Comment by NeverMin** [comment]
是的. 但体验不好, 连他们自己家的后台都很难用.

Philip Jay Fry <notifications@github.com> 于2018年5月29日周二 上午11:01写道：
