### ISSUE TITLE
想在mojo-weixin 的基础上写自己的脚本，对应的接收消息的事件怎么监听？

### ISSUE THREAD

**Issue by hidejack** [sjdy521/Mojo-Weixin#162]
抱歉，只找到api 调用接口，没弄明白事件如何监听触发？

**Comment by sjdy521** [comment]
事件的监听采用的时候两种方式：
1、你提供一个url的地址（需要自己实现http server服务，提供一个可以访问的url地址） 当事件产生的时候，会通过HTTP POST方法请求你的url，消息内容是通过请求的body携带过去

2、Openwx本身会开启一个本地的http server，你直接通过HTTP GET方式去请求这个地址，没有事件的时候请求会挂起等待，没有响应，直到超时后你需要重新发起新的请求，一旦有事件，会马上返回，结果在响应的http body里
