### ISSUE TITLE
请问如何同时启用webqq和webweixin？

### ISSUE THREAD

**Issue by go1574587** [sjdy521/Mojo-Weixin#163]
试了下在一个pl脚本里分别输入qq和微信，好像行不通

**Comment by dadiyang** [comment]
QQ和微信不是同一个项目，得起两个服务才行。
https://github.com/sjdy521/Mojo-Webqq

**Comment by sjdy521** [comment]
@go1574587 这两个项目采用的都是单线程异步框架，支持统一的事件驱动，理论上可以在一个pl里启动qq和微信，但是非常不推荐这样操作，建议单独两个pl单独运行
