### ISSUE TITLE
加了小冰以后，启动后接收消息报错

### ISSUE THREAD

**Issue by Anry** [sjdy521/Mojo-Weixin#164]
[warn] https://webpush.wx2.qq.com/cgi-bin/mmwebwx-bin/synccheck?r=1529918289134&skey=&sid=RVIImlhxhxJfuQr1&uin=31852615&deviceid=e943699883006957&synckey=1_671543056%7C2_671543088%7C3_671543059%7C11_671543009%7C201_1529918262%7C1000_1529915042%7C1001_1529915113%7C2001_1529480143&_=1529918289134 请求失败: - Bad response start-line

**Comment by sjdy521** [comment]
@Anry 这个是偶尔的网络接收消息请求异常，只要不是频繁发生影响正常功能，可以忽略，不影响使用
