### ISSUE TITLE
Mojo::Weixin::Plugin::PostQRcode发送邮件失败

### ISSUE THREAD

**Issue by Anry** [sjdy521/Mojo-Weixin#165]
使用QQ邮箱smtp=>"smtp.qq.com",port=>"465",from=>"***",to=>"****",user=>"****",pass=>"****",tls=>0

设置tls为0的话，Inactivity timeout
这是tls为1的话就报错[error] 插件[Mojo::Weixin::Plugin::PostQRcode]邮件发送失败: Error: ��ʹ����Ȩ���¼�������뿴: http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256

**Comment by dadiyang** [comment]
你的QQ邮箱需要使用授权码，而不是密码。现在很多邮箱都要求客户端使用授权码登录了。提示的链接写得很清楚。

**Comment by sjdy521** [comment]
已解决
应该是`pass=>"xxx" `里包含` @ $ `等perl特殊字符，在双引号下会引起读取字符串异常，建议改成单引号内 `pass=> 'xxx' `
