### ISSUE TITLE
微信接收压缩文件后，zip文件解压失败

### ISSUE THREAD

**Issue by wdsjxh** [sjdy521/Mojo-Weixin#171]
微信接收压缩文件后，zip文件解压失败，提示数据错误，文件被破坏，这块代码哪里改动
@sjdy521

**Comment by tusooa** [comment]
可能是写入文件时没有 `binmode`。

**Comment by sjdy521** [comment]
看下是偶尔问题还是一直存在，另外确认下zip文件大小是否为0 有时候从微信拿到得文件就是0 这个就没办法
