### ISSUE TITLE
安装mojo::Webqq之后安装MOJO::weixin出现错误

### ISSUE THREAD

**Issue by MasterOfStar** [sjdy521/Mojo-Weixin#172]
错误信息如下
[root@SafeFirst-VM ~]# cpanm Mojo::Weixin
--> Working on Mojo::Weixin
Fetching http://www.cpan.org/authors/id/S/SJ/SJDY/Mojo-Weixin-1.4.1.tar.gz ... OK
Configuring Mojo-Weixin-v1.4.1 ... OK
==> Found dependencies: IO::Socket::SSL
--> Working on IO::Socket::SSL
Fetching http://www.cpan.org/authors/id/S/SU/SULLR/IO-Socket-SSL-2.059.tar.gz ... OK
Configuring IO-Socket-SSL-2.059 ... OK
==> Found dependencies: Net::SSLeay
--> Working on Net::SSLeay
Fetching http://www.cpan.org/authors/id/M/MI/MIKEM/Net-SSLeay-1.85.tar.gz ... OK
Configuring Net-SSLeay-1.85 ... OK
Building and testing Net-SSLeay-1.85 ... FAIL
! Installing Net::SSLeay failed. See /root/.cpanm/work/1536223966.839/build.log for details. Retry with --force to force install it.
! Installing the dependencies failed: Module 'Net::SSLeay' is not installed
! Bailing out the installation for IO-Socket-SSL-2.059.
! Installing the dependencies failed: Module 'IO::Socket::SSL' is not installed
! Bailing out the installation for Mojo-Weixin-v1.4.1.

**Comment by MasterOfStar** [comment]
日志一并贴上
[root@SafeFirst-VM ~]# vim /root/.cpanm/work/1536223966.839/build.log
cpanm (App::cpanminus) 1.7044 on perl 5.010001 built for x86_64-linux-thread-multi
Work directory is /root/.cpanm/work/1536223966.839
You have make /usr/bin/make
You have LWP 5.833
You have /bin/tar: tar (GNU tar) 1.23
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
You have /usr/bin/unzip
Searching Mojo::Weixin () on cpanmetadb ...
--> Working on Mojo::Weixin
Fetching http://www.cpan.org/authors/id/S/SJ/SJDY/Mojo-Weixin-1.4.1.tar.gz
-> OK
Unpacking Mojo-Weixin-1.4.1.tar.gz
Entering Mojo-Weixin-1.4.1
Checking configure dependencies from META.json
Checking if you have ExtUtils::MakeMaker 6.58 ... Yes (7.34)
Configuring Mojo-Weixin-v1.4.1
Running Makefile.PL
"~/.cpanm/work/1536223966.839/build.log" 161L, 8379C          1,1           Top

**Comment by NeverMin** [comment]
请参考 [README.md](https://github.com/sjdy521/Mojo-Weixin/blob/master/README.md) 文件 SSL 部分.

**Comment by MasterOfStar** [comment]
执行检查之后仍然失败
[root@SafeFirst-VM ~]# curl -ks "https://raw.githubusercontent.com/sjdy521/Mojo-Weixin/master/script/check_dependencies.pl"|perl -
Checking dependencies ...
--------------------------------
Term::ANSIColor           is ok
IO::Socket::SSL           is ok
IO::Compress::Gzip        is ok
Time::Piece               is ok
Encode::Locale            is ok
Time::Seconds             is ok
Time::HiRes               is ok
Crypt::OpenSSL::RSA       is ok
Compress::Raw::Zlib       is ok
Crypt::OpenSSL::Bignum    is ok
Digest::MD5               is ok
Digest::SHA               is ok
--------------------------------
Check result: 12/12
Congratulations, all dependencies is ok
[root@SafeFirst-VM ~]# cpanm Mojo::Weixin
--> Working on Mojo::Weixin
Fetching http://www.cpan.org/authors/id/S/SJ/SJDY/Mojo-Weixin-1.4.1.tar.gz ... OK
Configuring Mojo-Weixin-v1.4.1 ... OK
==> Found dependencies: IO::Socket::SSL
--> Working on IO::Socket::SSL
Fetching http://www.cpan.org/authors/id/S/SU/SULLR/IO-Socket-SSL-2.059.tar.gz ... OK
Configuring IO-Socket-SSL-2.059 ... OK
==> Found dependencies: Net::SSLeay
--> Working on Net::SSLeay
Fetching http://www.cpan.org/authors/id/M/MI/MIKEM/Net-SSLeay-1.85.tar.gz ... OK
Configuring Net-SSLeay-1.85 ... OK
Building and testing Net-SSLeay-1.85 ... FAIL
! Installing Net::SSLeay failed. See /root/.cpanm/work/1536235879.10790/build.log for details. Retry with --force to force install it.
! Installing the dependencies failed: Installed version (1.35) of Net::SSLeay is not in range '1.46'
! Bailing out the installation for IO-Socket-SSL-2.059.
! Installing the dependencies failed: Installed version (1.31) of IO::Socket::SSL is not in range '1.94'
! Bailing out the installation for Mojo-Weixin-v1.4.1.

**Comment by sjdy521** [comment]
cpanm IO::Socket::SSL 执行这个命令单独安装下这个模块就行了

**Comment by MasterOfStar** [comment]
cpanm IO::Socket::SSL
这个一直出错误
log如下：
Written by John Gilmore and Jay Fenlason.
You have /usr/bin/unzip
Searching IO::Socket::SSL () on cpanmetadb ...
--> Working on IO::Socket::SSL
Fetching http://www.cpan.org/authors/id/S/SU/SULLR/IO-Socket-SSL-2.059.tar.gz
-> OK
Unpacking IO-Socket-SSL-2.059.tar.gz
Entering IO-Socket-SSL-2.059
Checking configure dependencies from META.json
Checking if you have ExtUtils::MakeMaker 6.58 ... Yes (7.34)
Configuring IO-Socket-SSL-2.059
Running Makefile.PL
Checking if your kit is complete...
Looks good
Warning: prerequisite Net::SSLeay 1.46 not found. We have 1.35.
Generating a Unix-style Makefile
Writing Makefile for IO::Socket::SSL
Writing MYMETA.yml and MYMETA.json
-> OK
Checking dependencies from MYMETA.json ...
Checking if you have Net::SSLeay 1.46 ... No (1.35 < 1.46)
Checking if you have Scalar::Util 0 ... Yes (1.21)
Checking if you have Mozilla::CA 0 ... Yes (20180117)
Checking if you have ExtUtils::MakeMaker 0 ... Yes (7.34)
==> Found dependencies: Net::SSLeay
Searching Net::SSLeay (1.46) on cpanmetadb ...
--> Working on Net::SSLeay
Fetching http://www.cpan.org/authors/id/M/MI/MIKEM/Net-SSLeay-1.85.tar.gz
-> OK
Unpacking Net-SSLeay-1.85.tar.gz
Entering Net-SSLeay-1.85
Checking configure dependencies from META.yml
Checking if you have ExtUtils::MakeMaker 6.58 ... Yes (7.34)
Configuring Net-SSLeay-1.85
Running Makefile.PL
*** Found OpenSSL-1.0.2k installed in /usr
*** Be sure to use the same compiler and options to compile your OpenSSL, perl,
    and Net::SSLeay. Mixing and matching compilers is not supported.
Do you want to run external tests?
These tests *will* *fail* if you do not have network connectivity. [n] n
Checking if your kit is complete...
说真的，现在没有什么一键脚本么。。。我记得之前gcm for mojo 那边有人写过来着

**Comment by sjdy521** [comment]
IO::Socket::SSL 这个问题最近折腾了很多人 这个模块通过编译安装的方式每个机器的环境都不一样，很难保证不出问题，我再想想办法，如果搞不定 可以找个时间让我远程帮忙安装下

**Comment by MasterOfStar** [comment]
我现在是在另一台Ubuntu的ovz机上弄好了。之前ctos换了三台都是这样，可能是系统问题？不过好像也有Ubuntu出错的。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: sjdy521 <notifications@github.com>
发送时间: Sunday, September 30, 2018 10:59:13 AM
收件人: sjdy521/Mojo-Weixin
抄送: MasterOfStar; Author
主题: Re: [sjdy521/Mojo-Weixin] 安装mojo::Webqq之后安装MOJO::weixin出现错误 (#172)


IO::Socket::SSL 这个问题最近折腾了很多人 这个模块通过编译安装的方式每个机器的环境都不一样，很难保证不出问题，我再想想办法，如果搞不定 可以找个时间让我远程帮忙安装下

―

**Comment by LeeReindeer** [comment]
同样的问题。。我安装了这两个依赖就好了
```
sudo apt-get install libio-socket-ssl-perl libnet-ssleay-perl
```

**Comment by ttimasdf** [comment]
RPi + Raspbian Stretch 相同报错，用 @LeeReindeer 方法可解决，thx 👍

**Comment by Techeek** [comment]
使用 @LeeReindeer 方法解决，太赞了！
