### ISSUE TITLE
centos7下安装失败

### ISSUE THREAD

**Issue by fenglinxiu** [sjdy521/Mojo-Weixin#174]
这是错误日志：
PERL_DL_NONLAZY=1 /usr/bin/perl "-MExtUtils::Command::MM" "-e" "test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
Connection error: Connect timeout at t/https.t line 17.
# Looks like your test exited with 115 before it could output anything.
t/https.t ........
Dubious, test returned 115 (wstat 29440, 0x7300)
Failed 1/1 subtests
t/load_module.t .. ok

Test Summary Report
-------------------
t/https.t      (Wstat: 29440 Tests: 0 Failed: 0)
  Non-zero exit status: 115
  Parse errors: Bad plan.  You planned 1 tests but ran 0.
Files=2, Tests=1, 16 wallclock secs ( 0.01 usr  0.00 sys +  0.36 cusr  0.04 csys =  0.41 CPU)
Result: FAIL
Failed 1/2 test programs. 0/1 subtests failed.
make: *** [test_dynamic] Error 255
-> FAIL Installing Mojo::Weixin failed. See /root/.cpanm/work/1537691074.53063/build.log for details. Retry with --force to force install it.
7 distributions installed

我也尝试过：cpanm Mozilla::CA（已经安装）
环境：虚拟机centos7，网络使用桥接模式

**Comment by sjdy521** [comment]
试试 cpanm IO::Socket::SSL 这个先安装成功之后 再来安装cpanm Mojo::Weixin
