### ISSUE TITLE
如何实现多账号登录？

### ISSUE THREAD

**Issue by citisy** [sjdy521/Mojo-Weixin#185]
我是perl新手，看到文档里面可以设置多账号登录，请问具体要怎样实现？

**Comment by sjdy521** [comment]
可以看下FAQ.md文件 里面有教程

**Comment by citisy** [comment]
你好，我可以通过只运行一次pl文件，运用类似多进程的方法来达到多账号登录这样的功能吗？

**Comment by sjdy521** [comment]
理论上可以 程序一开始的架构也是考虑支持这样的 但是单进程两个账号代码会彼此互相影响 一个账号代码阻塞会导致另外一个账号也无法正常收发消息 后来就不建议这样做 文档里也没有体现了

**Comment by citisy** [comment]
好的，谢谢解答~
