### ISSUE TITLE
docker镜像没有查看登录二维码的接口?

### ISSUE THREAD

**Issue by leiguorui** [sjdy521/Mojo-Weixin#186]
希望在sjdy521/mojo-weixin镜像中,  能通过http接口直接访问到mojo_weixin_qrcode_default.jpg

**Comment by sjdy521** [comment]
当前受限于软件框架的问题，暂时做不到，后续会考虑一下
目前是通过 https://github.com/sjdy521/Mojo-Weixin/blob/master/Controller-API.md 实现的二维码文件下载api，但是这个没有制作镜像，可以自己做一个
