### ISSUE TITLE
收到无法识别消息代码【3】

### ISSUE THREAD

**Issue by wdsjxh** [sjdy521/Mojo-Weixin#187]
收到无法识别消息代码【3】，已将其忽略，
![qq 20181030155400](https://user-images.githubusercontent.com/17082762/47703765-422ac000-dc5c-11e8-8ebc-962649247f5e.jpg)

**Comment by sjdy521** [comment]
需要启动参数里增加一个 http_debug => 1 才知道这个无法识别的消息内容到底是什么
Mojo::Weixin->new(http_debug=>1)
