### ISSUE TITLE
docker使用如何开启多客户端

### ISSUE THREAD

**Issue by HuJunPariSmile** [sjdy521/Mojo-Weixin#189]
启动docker 自动是3000端口，不是2000，而且直接进入等待扫码的状态，如何使用多客户端API 手动来触发，同时问下群号多少，那个QQ群的链接唤醒不来qq

**Comment by sjdy521** [comment]
参见 https://github.com/sjdy521/Mojo-Weixin/blob/master/Controller-API.md
