### ISSUE TITLE
1.4.3版本网页登陆持续不到一天会被踢掉

### ISSUE THREAD

**Issue by Brightchu** [sjdy521/Mojo-Weixin#193]
服务端升级了1.4.3版本后，不能登陆超过一天，报了几行warning，微信客户端显示网页登陆被踢掉了。以前登陆一个礼拜都没有问题啊。不知道是什么原因，我安装回1.4.2的版本，有大量transaction插件的warning, 之前好像是没有的。
![image](https://user-images.githubusercontent.com/4463531/49910812-16d3fb80-febf-11e8-98a7-5884f028fa06.png)

**Comment by Brightchu** [comment]
我换回了1.4.2版本，把transcation插件的warning注释了。微信登陆又变稳定了。所以，应该是1.4.3版本导致微信登陆不到一天就出错被踢掉。

**Comment by sjdy521** [comment]
具体是报什么warning

**Comment by Brightchu** [comment]
> 具体是报什么warning

就是截图里那个

**Comment by YyItRoad** [comment]
1.4.3版本，运行起来没多久就报这个错了！

**Comment by sjdy521** [comment]
Hi All 非常抱歉这个严重问题困扰大家，目前v1.4.5版本已经修复了该问题
原因是微信出现“对方正在输入”提示的时候，微信接收消息接口就会得到一个异常响应，引起程序终止
目前已经修复了问题，不会引起程序终止，但是接口异常仍然会给出“Bad response start-line”，可以无视

**Comment by Brightchu** [comment]
> Hi All 非常抱歉这个严重问题困扰大家，目前v1.4.5版本已经修复了该问题
> 原因是微信出现“对方正在输入”提示的时候，微信接收消息接口就会得到一个异常响应，引起程序终止
> 目前已经修复了问题，不会引起程序终止，但是接口异常仍然会给出“Bad response start-line”，可以无视

谢谢。祝你生日快乐。晚了两天哈。
