### ISSUE TITLE
 [error] 获取联系人信息失败

### ISSUE THREAD

**Issue by kalujee** [sjdy521/Mojo-Weixin#2]
扫描二维码后点击登录，显示获取联系人失败。然后又重新生成二维码要求重新登录，请问是什么情况呢？

**Comment by sjdy521** [comment]
@kalujee 
这种现象已经有人反馈了，我已经定位到了bug，正在修复中，修复后会再通知你协助测试确认

**Comment by sjdy521** [comment]
@kalujee 此bug已经修复，请更新到1.0.2版本，还请测试下是否ok
https://github.com/sjdy521/Mojo-Weixin/commit/a3933e38075cb7409bdc24e0efa4360620e9be97

**Comment by kalujee** [comment]
@sjdy521 ok! 感谢了哈！

**Comment by LUAgam** [comment]
[19/04/29 08:17:16] [error] 获取通讯录联系人信息失败
更新了最新的版本还是不行
