### ISSUE TITLE
Java客户端

### ISSUE THREAD

**Issue by dadiyang** [sjdy521/Mojo-Weixin#201]
Java调用OpenWx的HTTP接口没有直接调用本地方法来得方便优雅，因此我封装了一个Java客户端，希望使用Java做微信客户端开发的同学能用得上。

https://github.com/dadiyang/wechat-client

可以的话，请 @sjdy521 推荐使用。

**Comment by sjdy521** [comment]
非常感谢 我会加入到项目的README中

**Comment by sjdy521** [comment]
已添加
