### ISSUE TITLE
/openwx/send_friend_message测试提示：没有那个文件或目录

### ISSUE THREAD

**Issue by dx8439** [sjdy521/Mojo-Weixin#205]
我的微信docker run起来之后# docker run -it  --env MOJO_WEIXIN_LOG_ENCODING=utf8 -p 3000:3000 --name wechat sjdy521/mojo-weixin，在本机做测试提示：# http://10.3.10.246:3000/openwx/send_friend_message?id=wxid_1sf5488py40712&content=hello 没有那个文件或目录

请问，没有文件夹或目录是什么意思？这个目录需要手动创建，然后下载插件吗？

**Comment by wglnngt** [comment]
看下有没有tmp文件夹。

**Comment by dx8439** [comment]
> 看下有没有tmp文件夹。

请求可以了，但返回值是空

# curl http://10.3.10.246:3000/openwx/send_friend_message?markname=飞&content=hello
[1] 37602
# {"code":100,"id":null,"status":"object not found"}

**Comment by wglnngt** [comment]
涉及汉字，用encodeURI或encodeURIComponent转码，直接写汉字不行的。

**Comment by wglnngt** [comment]
自己用的一个发消息的小脚本供参考下。可以直接发个人消息，群体消息，发送文件附件（发送文件时消息内容置空）。
`@if (0)==(0) echo off
setlocal enabledelayedexpansion

set "strName="
set "strMsg="
set "strType="
set "strFile="
if "%~1" NEQ "" (
	for /f "delims=" %%i in ('cscript -nologo -e:jscript %~s0 "%~1"') do (
		set "strName=%%i"
	)
) else (
	echo,Usage:
	echo,%~n0 Name Message Type[0:friend, 1:group] FilePath
	pause
	goto :EOF
)

if "%~2" NEQ "" (
	for /f "delims=" %%i in ('cscript -nologo -e:jscript %~s0 "%~2"') do (
		set "strMsg=%%i"
	)
)

if "%~4" NEQ "" (
	for /f "delims=" %%i in ('cscript -nologo -e:jscript %~s0 "%~4"') do (
		set "strFile=%%i"
	)
)

if "!strName!" NEQ "" if "!strMsg!" NEQ "" (
	if "%~3" EQU "1" (
		set "strType=group"
	) else (
		set "strType=friend"
	)
	echo,Name    : !strName!
	echo,Message : !strMsg!
	curl.exe "http://localhost:3000/openwx/send_!strType!_message" -d "displayname=!strName!&content=!strMsg!"
) else (
	if "!strName!" NEQ "" if "!strFile!" NEQ "" (
		if "%~3" EQU "1" (
			set "strType=group"
		) else (
			set "strType=friend"
		)
		echo,Name  : !strName!
		echo,Media : !strFile!
		curl.exe "http://localhost:3000/openwx/send_!strType!_message" -d "displayname=!strName!&media_path=!strFile!"
	) else (
		echo,Error parameters...
		ping -n 4 127.1>nul
	)
)

goto :EOF
@end

var arg = WScript.Arguments(0)
WScript.Echo( encodeURIComponent(arg) );
`
示例：
发送消息给“张三”
> SendWXMsg.bat "张三" "测试消息"

发送消息给群“三千世界”
> SendWXMsg.bat "三千世界" "虽然不明白，但感觉很厉害的样子……" 1

给“张三”发送“e:\temp\0002.png”文件
> SendWXMsg.bat "张三" "" 0 "e:\temp\0002.png"

给”三千世界“发送"e:\temp\0002.png"文件
> SendWXMsg.bat "三千世界" "" 1 "e:\temp\0002.png"

参数内容无空格，引号可省略。

**Comment by wglnngt** [comment]
bash脚本获取URI编码：
`echo -n 编码字符 | xxd | tr -d ' ' | sed "s/.*:\([^\.]*\)\..*/\1/;s/../%&/g"`

**Comment by sjdy521** [comment]
bat环境下输入的中文参数可能默认是gbk编码？中文需要utf8编码做urlencode才可以
