### ISSUE TITLE
发送消息测试，返回是空，请问是什么原因？

### ISSUE THREAD

**Issue by dx8439** [sjdy521/Mojo-Weixin#207]
# curl http://10.3.10.246:3000/openwx/send_friend_message?markname=飞&content=hello
[1] 37602
# {"code":100,"id":null,"status":"object not found"}

消息发送失败，返回为空。

**Comment by opengpu** [comment]
解决了吗？怎么解决的？

**Comment by opengpu** [comment]
@dx8439
