### ISSUE TITLE
Base.pm

### ISSUE THREAD

**Issue by Antisunny** [sjdy521/Mojo-Weixin#21]
attr子程序的
```Perl
return exists $_[0]{$attr} ? $_[0]{$attr} : ($_[0]{$attr} = $value)
          if @_ == 1;
```
这句永远都不会被执行吧

**Comment by sjdy521** [comment]
Mojo::Weixin::Base的代码 是从 [Mojo::Base](https://metacpan.org/pod/Mojo::Base)  拷贝而来的，代码本身是经过无数检验的，一般是不会有什么问题的，为何说这句永远不会被执行？
