### ISSUE TITLE
运行程序后，按数字键1（主键盘区），就自动弹出监听程序，如何取消此热键？

### ISSUE THREAD

**Issue by wglnngt** [sjdy521/Mojo-Weixin#210]
如题，数字键是常用键，使用频率很高的，每次一按数字1就会切换到Mojo-Weixin窗口上，非常不方便，请问如何修改此响应？

**Comment by sjdy521** [comment]
一般都不会特意绑定热键的 是不是你自己系统的特殊设置问题

**Comment by wglnngt** [comment]
> 一般都不会特意绑定热键的 是不是你自己系统的特殊设置问题

没有啊。关掉mojo-weixin窗口就正常了。只要一打开，按主键盘区的数字1键就会弹出mojo-weixin窗口来。

**Comment by sjdy521** [comment]
未知问题，无法给出更多建议
