### ISSUE TITLE
[Help]How to send message to a friend of wechat on Windows, called by the other C++ Exe?

### ISSUE THREAD

**Issue by opengpu** [sjdy521/Mojo-Weixin#212]
[Help]How to send message to a friend of wechat on Windows, called by the other C++ Exe?

**Comment by bollwarm** [comment]
you can use HTTPS API , The doc:

https://github.com/sjdy521/Mojo-Weixin/blob/master/API.md

**Comment by opengpu** [comment]
我把c++程序和mojo都先启动，然后在需要的时候在c++程序里发送https消息给mojo？然后mojo就会给微信的好友发消息？

**Comment by opengpu** [comment]
c++程序和mojo本身不需要互相通信对吧？甚至c++程序和mojo在不同的机器上也可以了？只要两个程序都在运行就行？

**Comment by opengpu** [comment]
其实两个程序都是在本地一台机器上的，但是我感觉mojo应该也要登陆然后一直运行，而且也无法和c++程序集成到一个程序里。
您知道有什么bot，对c++比较友好么，我看到的都是python，或者js的。
但其实无所谓，应该都需要把两个程序同时启动起来运行着。

**Comment by bollwarm** [comment]
不需要，你通过c++或者其他语言操作访问接口即可

**Comment by opengpu** [comment]
这么强大？？这应该是两个单独的程序啊。。怎么直接访问接口？？有教程或者demo么，谢谢

**Comment by bollwarm** [comment]
上面不是给你发了API文档了么

**Comment by opengpu** [comment]
哦哦，谢谢。主要我对perl完全不懂。。难得遇到大神，想直接问比较快。
主要很着急用。

**Comment by tusooa** [comment]
肯定看文档快啊。

**Comment by opengpu** [comment]
哦好的，谢谢。主要想先确定可行性。少走弯路。




------------------ 原始邮件 ------------------
发件人: "tusooa"<notifications@github.com>;
发送时间: 2019年4月26日(星期五) 凌晨0:26
收件人: "sjdy521/Mojo-Weixin"<Mojo-Weixin@noreply.github.com>;
抄送: "Tesla"<opengpu@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [sjdy521/Mojo-Weixin] [Help]How to send message to a friend ofwechat on Windows, called by the other C++ Exe? (#212)




肯定看文档快啊。
