### ISSUE TITLE
发送消息失败。。

### ISSUE THREAD

**Issue by opengpu** [sjdy521/Mojo-Weixin#214]
用程序发http消息没反应 返回失败。在windows10里的cmd里用curl测试，错误信息如下：

curl http://127.0.0.1:3000/openwx/send_friend_message?id=xxxx&content=hello
{"code":100,"id":null,"status":"object not found"}'content' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

curl http://127.0.0.1:3000/openwx/send_friend_message?markname=xxx&content=%e4%bd%a0%e5%a5%bd
curl: (52) Empty reply from server
'content' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by wglnngt** [comment]
命令提示符或批处理状态下与字符号"&"被当成逻辑执行符号。要么加转义符"^"对与字符进行转义，要么在链接两旁加上引号。
