### ISSUE TITLE
如何确定好友的唯一性？

### ISSUE THREAD

**Issue by zane0113** [sjdy521/Mojo-Weixin#215]
如题，我测试每次扫码好友跟群组ID都是不同的，请问如何获取wxid呢

**Comment by zane0113** [comment]
uid也是空的，那怎么确定微信好友身份唯一呢？

**Comment by sjdy521** [comment]
没办法 只能用备注名称来区分 尽量取个不容易重复的备注名称吧

**Comment by opengpu** [comment]
备注名称是中文怎么办？发送失败，需要传给mojo什么编码的中文字符串

**Comment by sjdy521** [comment]
需要把原始中文utf8编码进行urlencode
