### ISSUE TITLE
cpanm - command not found - macOS, perl 5.28

### ISSUE THREAD

**Issue by tddschn** [sjdy521/Mojo-Weixin#217]
I was on mac and following the instruction in the README.

1. install perl: I didn't do anything since perl was already installed on mac (version 5.28)
2. install cpanminus: I used cpan to do it and cpanminus was successfully installed.

```
$ cpan -i App::cpanminus
Loading internal logger. Log::Log4perl recommended for better logging
Reading '/Users/me/.cpan/Metadata'
  Database was generated on Sat, 25 May 2019 02:56:31 GMT
App::cpanminus is up to date (1.7044).
```
3. 
```
$cpanm
zsh: command not found: cpanm
```

I don't know a lot about perl or cpan/cpanm, and couldn't figure out what's wrong.

can anyone help me with this?

thanks in advance!!

**Comment by bollwarm** [comment]
cpanm not cpamn

**Comment by tddschn** [comment]
well, I mistyped it. 
![image](https://user-images.githubusercontent.com/45612704/58393104-ae916480-806f-11e9-8e7d-6c89f204d4ce.png)

**Comment by myjeshurun** [comment]
I have the same problem too.

**Comment by sjdy521** [comment]
`cpan -I App::cpanminus` is specially for root user.
you can try this way to install cpanm `curl -kL http://cpanmin.us | perl - App::cpanminus`
this will install cpanm into `~/perl5/bin/cpanm`

**Comment by stradicat** [comment]
I installed it that way, but it's still not found.

My `zshrc` contains the userland config line `eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib=$HOME/perl5)"`.

**Comment by somk** [comment]
已经收到。
