### ISSUE TITLE
发送位于本地机器中的图片

### ISSUE THREAD

**Issue by opengpu** [sjdy521/Mojo-Weixin#219]
http://127.0.0.1:3000/openwx/send_friend_message?id=xxx&media_path=https%3a%2f%2fss0.bdstatic.com%2flogo.png
应该改为使用：
http://127.0.0.1:3000/openwx/send_friend_message?id=xxx&media_path=E:/Downloads/test.png
对么？

**Comment by opengpu** [comment]
https://github.com/sjdy521/Mojo-Weixin/issues/116
另外，这个是由于微信每天有发送图片的数量限制？

**Comment by sjdy521** [comment]
@opengpu 发送本地文件的直接写本地路径，但是要注意urlencode
每天发送数量限制这个需要自己摸索，我没有发过那么多图片，也不清楚是否有限制
