### ISSUE TITLE
怎么通过C++程序关闭mojo-weixin？？

### ISSUE THREAD

**Issue by opengpu** [sjdy521/Mojo-Weixin#220]
怎么通过C++程序关闭mojo-weixin？
我在windows中自己的程序启动的时候通过代码运行.bat启动的mojo，想在关闭c++程序的时候也自动关闭mojo-weixin，请问如何做？是kill进程么，哪个进程呢？

**Comment by opengpu** [comment]
有人知道吗？

**Comment by bollwarm** [comment]
找/tmp下的 pid文件，文件里就是进程号

**Comment by NeverMin** [comment]
他是 Windows

Orange <notifications@github.com> 于2019年6月11日周二 下午4:28写道：

**Comment by opengpu** [comment]
嗯对，而且记得之前试过。忘了当时什么问题，然后提示的进程号和实际的进程号并不一样，任务管理器里没有。当时作者说是bug。貌似是当时登录不上还是什么问题遇到的来着

**Comment by opengpu** [comment]
那就只能手动关闭了么。。。大伙有什么好办法么。。二维码那个图片浏览软甲你貌似是得手动关闭了。。

**Comment by opengpu** [comment]
https://stackoverflow.com/questions/56576939/open-a-process-and-capture-screen-of-its-area-in-c-on-windows-using-qt
查到这个方法了，但是mojo支持么

**Comment by opengpu** [comment]
有人知道么？

**Comment by sjdy521** [comment]
可以尝试加载Openwx插件，然后调研客户端终止的api来关闭程序
https://github.com/sjdy521/Mojo-Weixin/blob/master/API.md#终止程序运行
