### ISSUE TITLE
每天凌晨自动退出登录？

### ISSUE THREAD

**Issue by Steven8558** [sjdy521/Mojo-Weixin#231]
不知道什么时候开始，每天凌晨大概2点到4点，就会自退出登录，每天早上都要重新扫码登陆。不知道怎么回事，是腾讯那边限制了吗？
<img width="484" alt="微信截图_20200426211954" src="https://user-images.githubusercontent.com/52463333/80308829-bf100900-8803-11ea-8ed7-340a51855967.png">

**Comment by hexsum** [comment]
是的 腾讯那边的限制，扫描的有效时间过期了
