### ISSUE TITLE
#导致发送信息中断

### ISSUE THREAD

**Issue by wususu** [sjdy521/Mojo-Weixin#26]
发送信息的时候,如果含有#字符,程序将会自动截去掉后面的所有内容

**Comment by sjdy521** [comment]
我先测试确认下哈

**Comment by sjdy521** [comment]
井号在url的规范里有特殊的用途，因此你需要将井号转义成%23，比如

http://127.0.0.1:3000/openwx/send_friend_message?id=xxx&content=hello%23world

> 参见RFC1738 http://www.ietf.org/rfc/rfc1738.txt
> 
> The character "#" is unsafe and should
>    always be encoded because it is used in World Wide Web and in other
>    systems to delimit a URL from a fragment/anchor identifier that might
>    follow it
