### ISSUE TITLE
Mojo::Webqq和Mojo::Weixin两个不能同时打开

### ISSUE THREAD

**Issue by linux0ne** [sjdy521/Mojo-Weixin#29]
一、Mojo::Webqq启动脚本：

#!/usr/bin/env perl
use Mojo::Webqq;
my $qq = 123456789;    #修改为你自己的实际QQ号码
my $client = Mojo::Webqq->new(qq=>$qq);
$client->load("ShowMsg");
$client->load("IRCShell"); #加载IRCShell插件
$client->run();

二、Mojo::Weixin启动脚本：

#!/usr/bin/env perl
use Mojo::Weixin;
my $client = Mojo::Weixin->new();
$client->load("ShowMsg");
$client->load("IRCShell",data=>{host=>"127.0.0.1",port=>8888,}); #加载IRCShell插件
$client->run();

正常来说，一个是监听6667端口，一个是8888端口，没有“占用”问题。
如果把webqq先启动了，这时6667就被使用了，可以被IRC客户端去连接的，没有问题。可这时，若把weixin也启动了，则正常登陆没有问题，若用IRC客户端去连接8888端口则无法实现，因为8888端口根本没有被监听……经测试，其实还是用着6667端口，只是因为被占用，而无法被IRC客户端连接……这就说明weixin在这种情况下的启动脚本是根本没有实现功能的。

怎么办？

**Comment by sjdy521** [comment]
已确认是由于IRCShell插件参数设置方式不正确导致的，文档示例也进行了修复
$client->load("IRCShell",data=>{
        listen=>[ {host=>"127.0.0.1",port=>8888,} ]
}); #加载IRCShell插件
