### ISSUE TITLE
Mojo::Weixin 可否加入好友table自动补全功能

### ISSUE THREAD

**Issue by linux0ne** [sjdy521/Mojo-Weixin#30]
情况
     好友名字中含有特殊字符，如表情之类，这样在程序识别的时候，就会出现如下例子：
陈[未知表情][未知表情]闯

如果/query nickname 这个格式的话，输入名字比较麻烦。

```
 提个方法 ：把好友的名字用编号代替，如1、2、3……55、73等 ，这样就可以用下面的格式开启新的单独窗口了/query 3
```

**Comment by lyrl** [comment]
你用终端聊天吗？

**Comment by sjdy521** [comment]
微信的名称中可以包含表情字符，会被翻译为[xxxx]的文本形式 ，出现 [未知表情] 是因为有些表情没有识别到，这方面会想办法改善

自动补全是在客户端自身实现的，要先确认下使用的irc客户端自身是否支持自动tab补全
比如“陈[未知表情][未知表情]闯”，输入 "/query 陈" 然后按tab键，理论上应该会自动补全为 “/query 陈[未知表情][未知表情]闯”

由于自动补全是客户端自身实现的，把好友的名字用编号代替，这个会考虑下服务端如何和客户端配合
既有编号，又能保证通过名称很好的识别好友的身份

**Comment by csrgxtu** [comment]
如果使用irssi客户端, 就有自动补全的功能. 如 /msg 黄 不停的按tab键就可以了.
