### ISSUE TITLE
多实例下，二维码能不能不要覆盖掉

### ISSUE THREAD

**Issue by kknono** [sjdy521/Mojo-Weixin#31]
多实例下，登陆二维码能不能不要覆盖掉。

**Comment by sjdy521** [comment]
https://github.com/sjdy521/Mojo-Weixin/blob/master/FAQ.md#2-如何运行多个微信账号

在FAQ中有提到多实例的问题，虽然把cookie覆盖的问题给考虑到了，但确实忽略了二维码互相覆盖的问题

感谢反馈，将会在加入修复计划，在下个commit进行修复

当前临时的解决方案是 在new的时候通过参数 qrcode_path 手动指定不同实例的二维码保存路径，来区分开，比如：

实例1： Mojo::Weixin->new(qrcode_path=>"aaaaa.jpg");
实例2：Mojo::Weixin->new(qrcode_path=>"bbbbb.jpg");

**Comment by sjdy521** [comment]
重新确认了一下代码，是我搞错了，程序目前已经考虑到多实例运行时的cookie和二维码覆盖的问题
请参考如下FAQ：

https://github.com/sjdy521/Mojo-Weixin/blob/master/FAQ.md#2-如何运行多个微信账号
