### ISSUE TITLE
新增群聊成员事件，能否知道新增成员的入群方式？比如谁邀请加入的或者扫码加入

### ISSUE THREAD

**Issue by xbzhao168** [sjdy521/Mojo-Weixin#32]
管理群时可能会有一些类似的分析功能

**Comment by sjdy521** [comment]
能否需求再具体描述下，如果比较常用，我可以考虑做成插件的形式发布出来

**Comment by sjdy521** [comment]
一切基于网页版，如果网页版支持获取到这些信息的话就可以 我有空研究下

**Comment by sjdy521** [comment]
目前测试确认微信群组有新成员加入时会产生一些系统的提示消息，比如：

> xxx邀请xxx加入了群聊
> xxx与群里其他人都不是微信朋友关系，请注意隐私安全

需要把这些基于文字的信息提取出来，进行分类，找出邀请者
总之，理论上获取这些信息是可行的，中秋有空我尝试先加入下这方面的信息支持

**Comment by sjdy521** [comment]
现在新增了群提示消息（group_notice）类型，可以获取到如下这类信息

> xxx邀请xxx加入了群聊
> xxx与群里其他人都不是微信朋友关系，请注意隐私安全

并且，消息上报api接口也已经支持，可以先尝试根据这类信息自己做邀请统计，参考API文档 

https://github.com/sjdy521/Mojo-Weixin/blob/master/API.md#6-自定义接收消息上报地址

``
群提示消息上报

connect to 127.0.0.1 port 4000
POST /post_api
Accept: */*
Content-Length: xxx
Content-Type: application/json

{   "receiver":"小灰",
    "time":"1442542632",
    "content":"你邀请灰太狼加入了群聊",
    "class":"recv",
    "receiver_id":"@4072574066",
    "group":"PERL学习交流",
    "group_id":"@@2617047292",
    "id":"10856",
    "type":"group_notice",
    "format": "text",
    "post_type": "receive_message"
}`
```
