### ISSUE TITLE
运行示例代码,一直循环登入->获取消息->登出

### ISSUE THREAD

**Issue by eleveni386** [sjdy521/Mojo-Weixin#36]
RT. 
运行
`#!/usr/bin/env perl
use Mojo::Weixin;
my ($host,$port,$post_api);

$host = "127.0.0.1"; #发送消息接口监听地址，修改为自己希望监听的地址
$port = 3000;      #发送消息接口监听端口，修改为自己希望监听的端口
#$post_api = 'http://xxxx';  #接收到的消息上报接口，如果不需要接收消息上报，可以删除或注释此行

my $client = Mojo::Weixin->new(log_level=>"info",http_debug=>0);
$client->load("ShowMsg");
$client->load("Openwx",data=>{listen=>[{host=>$host,port=>$port}], post_api=>$post_api});
$client->run();
`
就一直是登入 登出
我是采用Mojo-ActivePerl-master 方式安装

**Comment by sjdy521** [comment]
你使用的Mojo-Weixin版本是多少 如果比较旧可以尝试升级到最新的1.2.1 看看问题有没有解决


发自网易邮箱大师
在2016年10月16日 17:09，eleven 写道:

RT.
运行

**Comment by sjdy521** [comment]
Mojo-ActivePerl自带的版本比较旧了 可以直接运行下 cpanm Mojo-Weixin 来升级到最新版本

**Comment by eleveni386** [comment]
恩, 折腾了半天终于可以跑起来了. perl没有 类似python的qrcode模块么. 如果我将机器人丢到vps上 每次都要将二维码下载回本地扫描 好麻烦的说.

**Comment by sjdy521** [comment]
有类似python的qrcode模块 最近刚有写成了一个插件 不过只在github上有 还没有发布到正式版（通过cpanm安装的）
$client->load("ShowQRCodeInTerm");
加到代码里即可

不过这个安装起来有些麻烦

另外 还有一个插件把二维码上传到云存储
$client->load("UploadQRcode");

获取到在线链接 浏览器直接打开查看

欢迎加群交流 这里讨论起来比较不方便
qq群 Mojo-Webqq
群号 498880156
