### ISSUE TITLE
只支持perl进行插件开发?

### ISSUE THREAD

**Issue by eleveni386** [sjdy521/Mojo-Weixin#37]
貌似只支持perl进行插件开发? openwx 只有发送API, 并无接收API, 如果要做一个机器人 除了用perl来开发, 还支持其他语言嘛?  

找到了openwx 有自定义消息上报接口. 可以close掉了

**Comment by sjdy521** [comment]
嗯 利用发送消息和上报消息的api你可以使用自己的语言来实现机器人或者设计自己的插件
