### ISSUE TITLE
关于机器人问题

### ISSUE THREAD

**Issue by eleveni386** [sjdy521/Mojo-Weixin#38]
今天准备开始写机器人 然后发现一个问题. 我注册了一个小号. 用来作为机器人. 然后手机扫描二维码登录之后, 我手机切换至主号上. 准备跟小号对话 来调试 发现 手机上小号刚退出 Mojo-weixin 就退出了. 接着我尝试 用主号 启动两个web 微信 (一个Mojo-weixin, 一个web 微信) 发现 只要第二个扫描认证后 登录 第一个已经登录的web 微信 就会自动退出. 而通过注册小号方式来做机器人 就要求 手机上的小号微信不能退出. 有点失落.. 这样没法玩了 555

**Comment by sjdy521** [comment]
我都是用自己的大号登录Mojo-Weixin 然后再在手机上发消息测试的 
手机上可以自己跟文件助手说话 或者 和微信团队 微软小冰 这种公众号说话 他们会自动回复你的


或者拉个讨论组让朋友帮忙发信息测试
或者就准备两部手机:-)


发自网易邮箱大师
在2016年10月18日 23:46，eleven 写道:

今天准备开始写机器人 然后发现一个问题. 我注册了一个小号. 用来作为机器人. 然后手机扫描二维码登录之后, 我手机切换至主号上. 准备跟小号对话 来调试 发现 手机上小号刚退出 Mojo-weixin 就退出了. 接着我尝试 用主号 启动两个web 微信 (一个Mojo-weixin, 一个web 微信) 发现 只要第二个扫描认证后 登录 第一个已经登录的web 微信 就会自动退出. 而通过注册小号方式来做机器人 就要求 手机上的小号微信不能退出. 有点失落.. 这样没法玩了 555

**Comment by sjdy521** [comment]
Mojo-Weixin就是基于web微信 所以同一个账号只能登录一种 另一个就会踢掉


另外还必须保持手机在线


发自网易邮箱大师
在2016年10月18日 23:46，eleven 写道:

今天准备开始写机器人 然后发现一个问题. 我注册了一个小号. 用来作为机器人. 然后手机扫描二维码登录之后, 我手机切换至主号上. 准备跟小号对话 来调试 发现 手机上小号刚退出 Mojo-weixin 就退出了. 接着我尝试 用主号 启动两个web 微信 (一个Mojo-weixin, 一个web 微信) 发现 只要第二个扫描认证后 登录 第一个已经登录的web 微信 就会自动退出. 而通过注册小号方式来做机器人 就要求 手机上的小号微信不能退出. 有点失落.. 这样没法玩了 555

**Comment by eleveni386** [comment]
恩, 基于这个特性. Mojo-weixin 不适合做机器人. 适合做客户端, 毕竟没那个人拿自己主号来当机器人给别人玩的吧. 单独小号的话 又要求手机在线

**Comment by sjdy521** [comment]
事实上很多人都是拿自己的主号在做机器人 不过主号本身就是一些公司宣传用的 如果是个人账号 偶尔拿来和朋友耍一下也可以 一般也不会拿来一直做公开的机器人




目前的用途：
1、定时发消息（品牌宣传 企业报警等）
2、linux上聊天用
3、机器人娱乐
4、做云服务，服务器运行多账号，提供账号的挂机+个性好玩的聊天插件等


发自网易邮箱大师
在2016年10月19日 12:28，eleven 写道:

恩, 基于这个特性. Mojo-weixin 不适合做机器人. 适合做客户端, 毕竟没那个人拿自己主号来当机器人给别人玩的吧. 单独小号的话 又要求手机在线
