### ISSUE TITLE
微信群组加载不全的问题

### ISSUE THREAD

**Issue by diandianqu** [sjdy521/Mojo-Weixin#39]
每次登陆都会提示更新群组，但是群组一般都更新不全，未更新的群，如果收到消息，能更新进来，但是这样一来就不能主动给很多群发消息了，而且下次微信重启的时候，上次未加载的群，依然没有被加载！

**Comment by sjdy521** [comment]
已修复，原因是在请求通讯录中的好友、群组信息时，有一个参数 seq=0是写死的，因为一开始并不清楚这个参数的作用，实际上才发现当好友、群组数量非常多的情况下，seq=0只能获取一部分，服务端会提示seq=1,seq=2.等，需要根据seq分批次发请求，才能够最终把通讯录信息全部获取到

请使用github最新代码测试看看

**Comment by sjdy521** [comment]
暂时只能通过群组置顶或者把群组添加到通讯录来实现登录后加载到所有群组的信息，不置顶或不在通讯录里的群组有可能登录后没办法马上获取到
