### ISSUE TITLE
openqq-client.pl 打印好友列表和收到的响应有乱码

### ISSUE THREAD

**Issue by thorqq** [sjdy521/Mojo-Weixin#4]
使用demo中的openqq-client.pl 打印好友列表、收到的响应有乱码，发送给对方是中文时，对方微信收到的也是乱码

好友:
璇煶鎻愰啋    gh_22b87fa7cb3c
寰俊鏀粯    @82c3efa759834c229f923d6cca657360

{"code":0,"status":"鍙戦€佹垚鍔?,"msg_id":1454936158172} at wc2.pl line 68

**Comment by sjdy521** [comment]
hi demo里的例子写的并不严谨，暂时只能在utf8编码的环境下工作，输入的要发送内容必须是utf8编码发送消息才不会乱码， 终端显示必须是utf8编码显示的内容才不会乱码

**Comment by sjdy521** [comment]
另外才发现我名字起错了… 应该叫openwx-client.pl
