### ISSUE TITLE
如何修改默认“小灰”的称呼？

### ISSUE THREAD

**Issue by liuzongquan** [sjdy521/Mojo-Weixin#40]
如题，如何修改默认“小灰”的称呼？

**Comment by sjdy521** [comment]
你说到是SmartReply插件吗

**Comment by liuzongquan** [comment]
是的，我看了一下貌似需要

**Comment by sjdy521** [comment]
智能回复后台对接的是图灵的api，你可以在图灵的官网注册一个帐号，会获取到一个apikey，还可以在图灵提供的后台去管理你的机器人，定制你机器人的名称 [图灵官网地址](http://www.tuling123.com/) 

获取到apikey之后，你可以修改你的xxx.pl文件 把这个apikey添加到SmartReply插件参数中，

`$client->load("SmartReply",data=>{apikey=>"xxxxxxxxxxxx"});`

保存文件，重启程序即可
