### ISSUE TITLE
这个可以获取到群号吗?

### ISSUE THREAD

**Issue by issmile** [sjdy521/Mojo-Weixin#42]
这个可以获取到群号吗?我看有人写的机器人可以获取群号的,下线后再登录群号也不变

**Comment by sjdy521** [comment]
基于网页版，目前看获取不到你说的群号（Uin） 官方屏蔽了


发自网易邮箱大师
在2016年11月13日 23:45，issmile 写道:

这个可以获取到群号吗?我看有人写的机器人可以获取群号的,下线后再登录群号也不变

**Comment by issmile** [comment]
好吧
