### ISSUE TITLE
可否实现日程管理

### ISSUE THREAD

**Issue by moboard** [sjdy521/Mojo-Weixin#43]
不知道可不中以实现一个可以交互的日程管理插件：

**时间**
获取现在时间(年月日周时分秒）

**日程/约会/生日/纪念日**
    什么时间 要做什么事 
**会议**
    会议时间 参会人员 会议主题

**备忘**
    如果需要很长一段时间后处理，则做一个备忘。参照以上。
    可以按标签列出（办公，家里，外出……）

**提醒方式**
    **时间：**单次提醒tmier/循环提醒interval
    **提醒途径：**
    微信个人消息 
    微信群消息（发到某一个群，适合有其他人参与的场景）
    QQ个人消息
    QQ群（发到某一个群，适合有其他人参与的场景）
    邮件（适合有其他人参与的场景，发送消息到相应人员的电子邮箱）

**应用实例**：
1、比如12月1日上午10：00要开销售会议，

**报时**  #可选。确定现在的日期时间
**指令 执行时间 主题 内容  提醒方式：时间&消息接受者**（不定义则发给自己，定义则用指定方式发给相关人员）
**todo 2016年12月1日10：00 销售会议**  参会人员A，B，C和D 。讨论客户开发及销售业绩总结。 **提醒方式:时间&群/个人/邮件**

**清单/list**  列出清单。
**编辑**（增加，修改，删除……）功能等

**Comment by moboard** [comment]
有看到  Net::ICal::Alarm            Data::ICal::Entry::Alarm，不知道能不能调用或者借鉴。

**Comment by sjdy521** [comment]
如果有哪些日历管理的平台开放api的话可以考虑对接来发送消息提醒
项目本身的核心定位还是在于“发送消息”，其他的逻辑最好能在外部实现

**Comment by moboard** [comment]
收发消息是基础功能，web微信就做得非常不错，这个项目做好了在收发消息功能上没办法超越他们原生的。
觉得可以考虑考虑在尽量实现原有功能上，做一些附加的、能补充微信QQ现在还没有的功能，这样可能会吸引用更多户。

日程管理的API，goodledo也有http://api.toodledo.com/。fullcalendar好像有API。
国内好像盛大麦库)http://open.note.sdo.com/)也有开放的API：

> 前段时间发布的麦库备忘（EasyDo）http://easydo.me/，就是一款基于麦库记事开放API开发的应用，麦库备忘（EasyDo）是一款用于处理待办事项，追求简单易用的备忘提醒应用。用户可以轻松的把要做的事情记录下来，并设置提醒，让您的工作任务、日程管理或者生活事项都更具条理和效率。由于基于开放平台的开发，麦库备忘（EasyDo）的后台和账号是完全贯通的。
