### ISSUE TITLE
查询好友中谁删除了自己

### ISSUE THREAD

**Issue by moboard** [sjdy521/Mojo-Weixin#44]
刚刚忘记写了，再建议实现一个功能。
微信里有很多悄悄把自己删除了的联系人，一个一个的去删除很费时间和力气。网传群发消息可以找出谁删除了你是不可行的。所以可不可以实现发条指令查询出谁删除了自己？然后再发一条指令删除这些已经删除了你的好友。
原是在一个python项目看到，利用微信网页版的接口, 将好友35人拉入一个群聊, 再移出, 反复进行多组, 无法成功拉入则说明他把你拉黑了，删除本来主有好友本来就有这个功能……

**Comment by sjdy521** [comment]
你说的python项目应该是指 [echat-deleted-friends](https://github.com/0x5e/wechat-deleted-friends)
这个项目的作者已经在README里说明了当前这个项目无法使用了

**Comment by moboard** [comment]
看了下python的那个项目，微信本身限制，效率太低了

**Comment by moboard** [comment]
好像还可以用吧，刚刚试了焉得虎子，还能查询好友关系之类的
