### ISSUE TITLE
小冰的微信号改了，XiaoiceReply插件出错

### ISSUE THREAD

**Issue by cocoakekeyu** [sjdy521/Mojo-Weixin#45]
小冰的微信号改为xiaoice-ms，XiaoiceReply插件没改，我对perl不熟，不知道怎么改插件。

![image](https://cloud.githubusercontent.com/assets/4177398/20469890/7cde61b8-afde-11e6-90c4-20a07f6071f4.png)

**Comment by sjdy521** [comment]
感谢反馈，问题已经修复

**Comment by cocoakekeyu** [comment]
下面这行的account是不是也要改，改插件这个代码就能用上小冰插件了吗。
之前试都没回复

![image](https://cloud.githubusercontent.com/assets/4177398/20474255/c41b9434-b000-11e6-9943-0e027524a1de.png)

**Comment by sjdy521** [comment]
不好意思，改的时候粗心大意了，已经按你的提示修改了，将在晚些时候和其他的改动一起提交
