### ISSUE TITLE
API 之 /openwx/stick "13. 设置或取消群组、好友置顶"

### ISSUE THREAD

**Issue by yixtan** [sjdy521/Mojo-Weixin#46]
返回「api not found」，这个 API 关闭了？

**Comment by sjdy521** [comment]
github上的改动会比较新，但代码没有包含在你安装的正式版里，所以你虽然可以在github上看到，但是无法使用

等正式版1.2.4发布的时候会添加进来，当前你可以尝试使用github最新代码进行测试，详见FAQ：
[如何使用github最新代码测试](https://github.com/sjdy521/Mojo-Weixin/blob/master/FAQ.md#3-如何使用github上最新的代码进行测试)
