### ISSUE TITLE
指定好友帐号发送消息，提示object not found

### ISSUE THREAD

**Issue by zjcnew** [sjdy521/Mojo-Weixin#47]
[root@mojowebqq ~]# curl -v "http://127.0.0.1:3000/openwx/send_friend_message?account=zjcnew&content=hi"
* About to connect() to 127.0.0.1 port 3000 (#0)
*   Trying 127.0.0.1... connected
* Connected to 127.0.0.1 (127.0.0.1) port 3000 (#0)
> GET /openwx/send_friend_message?account=zjcnew&content=hi HTTP/1.1
> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.21 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> Host: 127.0.0.1:3000
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: application/json;charset=UTF-8
< Date: Wed, 23 Nov 2016 07:50:08 GMT
< Content-Length: 54
< Server: Mojolicious (Perl)
< 
* Connection #0 to host 127.0.0.1 left intact
* Closing connection #0
{"code":100,"msg_id":null,"status":"object not found"}[root@mojowebqq ~]#

**Comment by sjdy521** [comment]
account属性并不是所有的情况下都可以获取到，并不可靠，可以先通过 /openwx/get_friend_info 查询下是否确实存在这样属性的好友对象

**Comment by zjcnew** [comment]
account不是指微信账号吧，那哪个属性是微信账号呢？


________________________________
发件人: sjdy521 <notifications@github.com>
发送时间: 2016年11月23日 19:52
收件人: sjdy521/Mojo-Weixin
抄送: zjcnew; Author
主题: Re: [sjdy521/Mojo-Weixin] 指定好友帐号发送消息，提示object not found (#47)


account属性并不是所有的情况下都可以获取到，并不可靠，可以先通过 /openwx/get_friend_info 查询下是否确实存在这样属性的好友对象

―

**Comment by sjdy521** [comment]
account是指微信号，但不一定能获取到，account可能是空
