### ISSUE TITLE
如何使用irrsi与好友或者在群里面聊天呢？

### ISSUE THREAD

**Issue by csrgxtu** [sjdy521/Mojo-Weixin#48]
你好，能否给一个简单的说明，如何在irrsi里面聊天。我可以通过 /msg username blabla发送消息， 但是朋友回发的消息不能在irssi展示出来。

**Comment by csrgxtu** [comment]
`/chat nickname` not working in irssi， when type this command, just send a text to the nickname user
`\u0001DCC CHAT CHAT 2130706433389079\u0001`

**Comment by sjdy521** [comment]
首先，通过这个项目运行起来的irc服务器（也就是你irssi连接到本机的irc服务器）是自己实现的，只实现支持了一些常用的聊天指令，并不支持全部的irc指令，因此/chat指令是不支持的

/msg nickname 的方式可以给irc帐号（你的好友）发送消息，但对方回复你的消息可能会在irssi上产生一个新的窗口 ，而不是在当前的窗口中，你需要检查下这点

另外，推荐使用 /query nickname 来打开一个和好友聊天的单独窗口，然后再进行聊天，多个窗口之间切换可以使用esc+数字

如果还有问题可以加群交流
