### ISSUE TITLE
IRCShell 连接其他的IRC频道

### ISSUE THREAD

**Issue by csrgxtu** [sjdy521/Mojo-Weixin#49]
请问在IRCShell里面可以链接其它的IRC频道吗，比如#ubuntu之类的。

**Comment by sjdy521** [comment]
你说的是连接IRCShell插件提供的本机127.0.0.1:6667端口的IRC服务器的#ubuntu
还是说连接其他IRC服务器（比如chat.freenode.net）的#ubuntu频道
加入一个频道，都是在你的irc客户端上直接操作就可以了 `/join #ubuntu` 
服务端不需要做什么事情呢

**Comment by csrgxtu** [comment]
可以的，只不过链接以后影响微信的使用了。

**Comment by csrgxtu** [comment]
哦， 我是想在连接着127.0.0.1:6667的时候，顺便连上irc.freenode.net， 然后既可以看微信，也可以看irc上的资源。

**Comment by sjdy521** [comment]
这个任何irc客户端都可以支持同时连接多个irc服务器的多个频道呀

**Comment by csrgxtu** [comment]
哦，知道了，谢谢。

**Comment by sjdy521** [comment]
你用的是哪个irc客户端呢
