### ISSUE TITLE
在irssi中发送图片文件

### ISSUE THREAD

**Issue by csrgxtu** [sjdy521/Mojo-Weixin#51]
我看到Mojo-Weixin的介绍说可以实现图片的接收发送, 所以我想在irssi里面直接发送图片,请问这可以做到吗?能否给个示例,或者需要修改IRCShell的实现,以支持这种操作.

**Comment by sjdy521** [comment]
因为irc协议本身就是专注纯文本聊天 所以发图片当前并不能直接支持 （但irc服务器是咱自己写的 所以没什么不可能）当前一般是自己把图片上上传到网络 再直接发urlgei对方

**Comment by sjdy521** [comment]
你也可以描述下你期望的发图操作方案 用户体验好的话 我来实现下

**Comment by wsdjeg** [comment]
@sjdy521 你说的这个方案不错，我想好呢该怎么给vim-chat实现这个功能了，哈哈。

**Comment by csrgxtu** [comment]
@sjdy521 我发现IRC Chenise模块实现了一些irc命令功能的实现，所以想通过在这里加入对话中文件发送功能，即用户在irc客户端会话中敲入：
`/file /tmp/my-stupid-dog.png`
就可以将图片发送到对方。不知道我的思路是否正确，如果你很忙，我也可以贡献。

**Comment by sjdy521** [comment]
这个思路我之前也想过，但有个比较麻烦的地方在于 大部分的irc客户端会检测你输入的irc指令 如果不支持就直接提示错误了
 /file 这个指令还没有发送到服务端就直接在客户端报错了 

所以我的想法倾向于 仍然使用客户端支持的指令 但在消息内容部分做自己的特殊处理 比如：
/msg :send-file xxxx.jpg

**Comment by sjdy521** [comment]
另外irc协议规范本身好像有个/dcc 的指令专门用于发送文件 可以研究下

**Comment by csrgxtu** [comment]
@sjdy521 我使用了dcc，在irssi里面不成功，发送过去只是文件名外加一点儿字符串，不是我想要的。我刚才在irssi里面和朋友的会话中敲入了下面命令：
`/file /tmp/dog.png`
没有报错。哦，不过像其他的irc客户端我就不知道了。不过定义二级命令的方式也是可以实现，只要对发送的消息进行模式匹配就可以实现。

**Comment by sjdy521** [comment]
不知道你测试的时候使用的是什么irc服务器，/file /dcc 我的Mojo::IRC::Server::Chinese还不支持哈
/file如果是标准的irc指令的话 也是可以运用一下，我找时间了解了解

**Comment by csrgxtu** [comment]
只要在IRCShell.pm添加发送图片的命令解析即可，即捕获irssi的输入，解析sendFile命令，然后调用send_media既可以发送。![效果图](https://github.com/csrgxtu/Drogo/raw/master/img/output.gif)

**Comment by eleveni386** [comment]
@csrgxtu 请提一个pr吧, 我也想要这个功能.

**Comment by csrgxtu** [comment]
@eleveni386 已经提交merge进入了主代码库了

**Comment by neila-a** [comment]
我建议用base64，把文件放在聊天信息里，也可以选择不接受文件，这样别的客户端虽然不能显示图片但也能显示base64码

**Comment by somk** [comment]
已经收到。
