### ISSUE TITLE
IRCShell收不到消息

### ISSUE THREAD

**Issue by eleveni386** [sjdy521/Mojo-Weixin#57]
用了IRCShell, 客户端使用的是irssi, 连接上我的vps, irssi提示连接成功, 然后/join 我的好友, 也成功了. 然后/query 私聊一个好友, 手机上没有同步消息. 然后对方也没有收到消息. 对方发送的消息. irssi上也无法收到. 通过vps上的终端查看. 是有内容来往的. 我的启动脚本如下:
#!/usr/bin/env perl
use Mojo::Weixin;
my $client = Mojo::Weixin->new();
$client->load("ShowMsg");
#$client->load("ShowQRCodeInTerm");
$client->load("UploadQRcode");
$client->load("IRCShell"); #加载IRCShell插件
$client->run();

另外对于如果我跑vps上 想24小时不离线, 安全性如何保证? 我看咱们这个IRC Server是开放式的. 没有什么授权机制, 或者密码之类的东西. 任何人只要知道我的IRC端口 都可以进入我的IRC Server ,如果此时他/join 我的好友 会发生什么?

**Comment by sjdy521** [comment]
当前插件存在一些问题，发送消息会报错，已经修复，详见commit：
https://github.com/sjdy521/Mojo-Weixin/commit/c797351e3848b03367267a9d2e609d3957c33812
可以用github最新的代码再测试下
https://github.com/sjdy521/Mojo-Weixin/blob/master/FAQ.md#3-如何使用github上最新的代码进行测试

对于安全性问题，后续会考虑做一下
1）IRC server的登录认证
2）IRC消息传输过程SSL加密
3）IP白名单限制等

当前建议IRC server只监听本机127.0.0.1网卡地址，这样只能够登录vps之后，连接本机IRC Server使用
或者建议IRC Server监听的端口不要使用默认的6667，换一个特殊的端口

**Comment by yqshao** [comment]
安全的问题可能可以暂时通过使用IRC Bouncer（比如ZNC或者Quassel）解决？
比如在VPS上运行ZNC，再从其他机器连接ZNC，而ZNC的端口可以设置SSL，密码认证等。
而IRCserver只监听127.0.0.1。

_其实用Bouncer的目的是为了可以同步历史记录，不过ZNC目前对Query的log有些问题，导致自己发送的信息不可见 @znc/znc#1269 。所以我现在用的是Quassel，可惜客户端有所限制，Irssi倒是有 Quassel 的模块可用_

**Comment by sjdy521** [comment]
@yqshao 感谢建议
IRC协议本身还是比较完善的，加密、认证等都支持，比较通用一些
你说的这些思路属于比较高级的玩法~有点厉害，我还都没玩过，有时间研究下
另，祝新春快乐

**Comment by yqshao** [comment]
确实，可以在IRCserver中实现加密会更好，使用起来也更灵活。
建议的方法也只能是作为变通的方法。
也祝新春快乐 🐔
