### ISSUE TITLE
不时发现 media_path = "non-exist-path"

### ISSUE THREAD

**Issue by yixtan** [sjdy521/Mojo-Weixin#58]
微信使用，遇到约有 10% 左右的 media 消息，media_path = "non-exist-path"，仅影响视频和表情，手机上可以查看，请问该如何解决？

**Comment by sjdy521** [comment]
这个通常是因为接收到了特殊表情 网页版不支持显示 获取到的数据大小为0 只能在手机上查看 可以不用管

**Comment by yixtan** [comment]
主要问题是其中一半是视频，手机能看到，但是上报的 json 里面 media_path = "non-exist-path"

**Comment by sjdy521** [comment]
设置下Mojo::Weixin->new(http_debug=>1)发些日志来看看吧 可以加群交流

**Comment by sjdy521** [comment]
近期这种现象又更多了
即使使用chrome浏览器网页访问，仍然存在类似的情况
暂时无解，继续观察
