### ISSUE TITLE
IRCShell的改进？

### ISSUE THREAD

**Issue by yqshao** [sjdy521/Mojo-Weixin#59]
首先感谢作者，这是我在使用过程中的一些想法，如果合理的话希望可以在后续采纳。

---
### 图片链接
现在的做法是向频道发送图片的本地位置，将图片链接发送到irc-server
我在使用时，觉得改成直接将图片消息替换成链接比较符合习惯，所以把发送PRIVMSG的部分改成了：
```perl
if (defined $image_api and $msg->format eq 'media' and $msg->media_size != 0){
        #过滤掉动画表情无法转换成链接的情况
        生成$link
        发送"[图片]$link"
}
else{
        发送"$line"
}
```
因为不熟悉perl，改的很烂，手动修改了每种发送，接收的代码，可能在收到msg的时候就直接替换会好一点。
### 群生成时的成员加入

现在的IRCShell在收到消息时才把成员加入群，这样不能正常在频道里查看成员，也就直接和在群中但不是好友的用户进行私信。
能否参考[wechatircd](
https://github.com/MaskRay/wechatircd)的行为，在建立频道时就将成员加入？
（虽然我在实际使用时也很少需要查看成员列表和与陌生人私信，但觉得这样更合理些）

**Comment by sjdy521** [comment]
图片链接的问题确实是我偷懒了，你建议的方式确实用户体验更好，我会尝试按照你的建议来完善下
不过也确实有其他用户在使用过程中关注irc上给出的是图片的本地文件路径，这样可以调用一些程序来访问本地的文件，另外考虑到上传图片采用的是第三方的图床服务，不一定100%可靠，会出现上传失败等问题，也需要考虑这种情况下要回退到本地文件路径，处理上逻辑要更复杂一些

另外，IRCShell插件github上的代码近期做了修改，image_api这个参数已经改名为upload_api了

建立频道时就将成员加入，以及irc服务器启动时就创建好友用户，这些都是可以实现的，但最开始的思路是认为这个并没有太大意义，因为现在并不能和陌生人私信，有点浪费操作，所以就没有设计成这样默认行为，而且当前内部代码有些性能问题（存在大量数组遍历等操作），短时间内大量创建irc虚拟用户对象会消耗非常长的时候，会导致irc服务器阻塞住很久，没办法响应其他客户端的正常指令，因此当初也没有选择这样做，需要先解决性能问题，再来提供一个可选的参数来控制是否默认把群成员或好友全部生成

感谢你的建议，会慢慢完善，个人精力有限，也希望你能多多贡献，

新春快乐~

**Comment by yqshao** [comment]
感谢详细的回复，我fork了代码，有时间仔细学习下，希望可以帮上忙。

**Comment by sjdy521** [comment]
@yqshao

**Comment by sjdy521** [comment]
@yqshao 
你提出的几个建议，已经实现了，代码改动比较大，也请多多帮忙测试下（需要使用github最新代码来测试）

参见 commit:
https://github.com/sjdy521/Mojo-Weixin/commit/9ce6c76d65ba85dfccba4a60ae651ae61fe67df5

1）在不设置 load_friend=>1的情况下, 使用 /query XXXX 时因为不存在该irc用户，服务端会直接返回 XXX no such nick，现在会再尝试从好友中搜索对应昵称的好友并创建irc用户，成功的话会收到类似这样的提示：

```[系统提示]已从QQ好友中搜索到对应昵称好友并生成irc用户，现在可以继续和好友聊天了```

2）上传媒体文件到图床，irc上接收到的消息会从

``` [图片](media/mojo_weixin_media_2uCq.jpg)``` 

变成 

``` [图片](https://ooo.0o0.ooo/2017/02/03/589432bdca8e9.jpg)```

**Comment by yqshao** [comment]
已经用上了新的代码，暂时没发现什么问题。
感觉可以close了。
