### ISSUE TITLE
openwx 接口建议增加功能

### ISSUE THREAD

**Issue by lkddi** [sjdy521/Mojo-Weixin#6]
建议增加群发功能。

**Comment by sjdy521** [comment]
具体是怎么个群发的方式？
比如一次性发给所有好友相同内容？

**Comment by lkddi** [comment]
是的，群发一样内容

**Comment by sjdy521** [comment]
@lkddi 所有好友都发送还是希望只是指定一部分好友发送，我需要考虑api的参数如何设计，有什么好建议吗

**Comment by lkddi** [comment]
可以全部好友，或者全部群，比如好友id=all就是全部好友。ID=100就是随机100好友

**Comment by sjdy521** [comment]
已经完成
`/openwx/send_friend_message?id=@all&content=hello`
