### ISSUE TITLE
media_id不起作用

### ISSUE THREAD

**Issue by kknono** [sjdy521/Mojo-Weixin#60]
http://xxxx:3001/openwx/send_friend_message?id=@4e773d1bb62f452e277de0fcf9dc0abd99a56049c7a989ba682a51e136704b4e&content=&media_id=735525768783102057:43

media_id是发送后取得的。
请求上面url报错：
{
code: 1,
id: 1486279302693,
media_id: "",
status: "unknown error"
}

**Comment by sjdy521** [comment]
你可以使用的有效media_id必须是你以前上传过或者发送过的，接收到的媒体的media_id不能直接拿来发送

**Comment by kknono** [comment]
嗯。请教个问题。media_data 这个字段是把语音/视频转了吧。如果需要在收到消息后，保存这个语音，通过这个media_data可以实现吗?

**Comment by sjdy521** [comment]
media_data是语音或视频等媒体的原始二进制数据 可以直接保存成文件就能打开或播放

不过程序本身在获取这些媒体数据的时候都有保存到本地临时文件

**Comment by sjdy521** [comment]
上报消息是media_data是被转成base64编码形式了，因为json不支持二进制数据，你可以转换后再保存成文件

**Comment by kknono** [comment]
谢谢。 另外语音，程序保存了mp3格式，而微信中的语音是silk格式的。 当转发语音的时候，在聊天对话框中显示的不是传统的语音样子了，还是一个页面，点击后（.mp3）才能播放。 有没有办法做到和传统的语音聊天那样。

**Comment by sjdy521** [comment]
@kknono 这个目前没办法，网页版微信不支持发送原生的语音，只能把mp3作为文件的形式发送
