### ISSUE TITLE
ShowQRCodeInTerm报错

### ISSUE THREAD

**Issue by yqshao** [sjdy521/Mojo-Weixin#61]
使用QRCodeInTerm会返回
`Not enough arguments for plot() at /home/alarm/Github/Mojo-Weixin/lib/Mojo/Weixin/Plugin/ShowQRCodeInTerm.pm line 26.`
应该是这个commit引起的 8e8285cefa0224186b538563085dbdc5013eeecf

**Comment by sjdy521** [comment]
最新github代码已修复

**Comment by sjdy521** [comment]
最新github代码已修复
