### ISSUE TITLE
服务启动2个小时就自动stop

### ISSUE THREAD

**Issue by kknono** [sjdy521/Mojo-Weixin#62]
服务启动2个小时就自动stop, 咋回事啊。是不是要配置什么东西。

**Comment by kknono** [comment]
阿里云 centos

**Comment by sjdy521** [comment]
已经解决了？发些运行日志来看下呀？

**Comment by sjdy521** [comment]
估计是手机端微信没有保持在线导致程序也被迫下线了，程序运行过程中必须保证手机端微信也在线
