### ISSUE TITLE
求助：发完消息自动退出

### ISSUE THREAD

**Issue by mxm145** [sjdy521/Mojo-Weixin#65]
我使用命令perl wx.pl &后台运行，但是只要调用发消息接口完成之后就会自动退出，监测的post_api接口地址也没有收到stop事件的消息，有人知道原因吗？发消息是在本机使用定时php调用send_message接口的

**Comment by kknono** [comment]
好像是的，我的也会自动停止

**Comment by bollwarm** [comment]
wx.pl是怎么写的，你执行完 perl wx.pl & 是不是后来把窗口管了

你可以加nohup用来解决这个问题

nohup perl wx.pl > log  2>&1 &

你调用接口，你查看当前目录下的log文件 less log 看执行过程信息和错误信息

建议装个screen 用screen -S webqq 进去然后启用，就不用加 & 关了也没事
你启用可以直接关闭窗口，或者通过ctrl+a d 退回shell窗口执行 调用api

然后你通过 screen -r webqq 可以返回哪个执行窗口看信息。

**Comment by sjdy521** [comment]
运行日志发出来看看

**Comment by mxm145** [comment]
@bollwarm 按照你说的确实没有退出了，谢谢回复，我再跑一段时间看看。我是跑在树莓派上的用putty连的，所以肯定是关了shell的
@sjdy521 不好意思没有开运行日志，把这个给忘记了，谢谢回复
