### ISSUE TITLE
微信无法显示全部群组

### ISSUE THREAD

**Issue by mrg1511104848** [sjdy521/Mojo-Weixin#66]
目前显示的只是第一次的webwxbatchgetcontact，火狐浏览器上是可以获取到全部的群组，他是通过多次请求这个地址，其中baserequest是不一样的。

如果有什么表述不清楚的地方，可以随时问我。我在群里 QQ1511104848

**Comment by csrgxtu** [comment]
我也遇到了这个问题，部分群组不见了。

**Comment by sjdy521** [comment]
`Mojo::Weixin->new(log_level=>"debug",http_debug=>1,log_path=>"日志保存路径");`
这样开启下debug日志，把日志提供给我分析下

**Comment by csrgxtu** [comment]
@sjdy521 如何给你日志，里面包含个人信息，可以不贴在这里吗？

**Comment by sjdy521** [comment]
@csrgxtu 感谢提供的日志 已经定位到问题原因了，我先尝试修复下，github代码提交后再通知你帮忙测试

**Comment by sjdy521** [comment]
@csrgxtu @mrg1511104848 
已经尝试修复获取群组不全的问题，参考commit https://github.com/sjdy521/Mojo-Weixin/commit/b7712b65a970e447b80d5e035f47a5273ada6735
可以参考FAQ https://github.com/sjdy521/Mojo-Weixin/blob/master/FAQ.md#3-如何使用github上最新的代码进行测试 使用github最新代码帮忙测试下

注意，在程序初始化的时候获取到的群组消息没有变动，仍然可能是不全的
但在微信运行过程中，服务端有返回了一些程序初始化时没有获取到的群组的id，此时程序会马上去更新相应的群组

**Comment by csrgxtu** [comment]
我找到原因了，我缺失的群组叫做   Share Knowledge  , 当我把群组名称改成  ShareKnowledge测试  就可以了。即，群组名称中间的空格不能正确处理。

**Comment by csrgxtu** [comment]
工作了，希望不是缓存之类的东西。

**Comment by sjdy521** [comment]
@csrgxtu 原来你的缺失是这方面，和我理解的完全不一样，irc上频道名有规范，空格之类的不支持
所以会被替换掉，但这并不影响使用，irc上的` ShareKnowledge`还是可以和微信上的`Share Knowledge`保持正确的联通的

**Comment by mrg1511104848** [comment]
我这边已经基本查明原因。是因为微信网页版需要发送一个通知到服务端通知手机，之后服务器通知网页版更新群组。具体请求的包地址是/cgi-bin/mmwebwx-bin/webwxstatusnotify

**Comment by mrg1511104848** [comment]
研究好几天了。终于有结果了。哈哈

**Comment by csrgxtu** [comment]
@mrg1511104848 你是用最新的代码，看看还会缺失不，我的缺失的群组已经可以显示了。
可以参考FAQ [https://github.com/sjdy521/Mojo-Weixin/blob/master/FAQ.md#3-如何使用github上最新的代码进行测试 ](可以参考FAQ https://github.com/sjdy521/Mojo-Weixin/blob/master/FAQ.md#3-如何使用github上最新的代码进行测试)
