### ISSUE TITLE
请增加ircserver的密码校验功能

### ISSUE THREAD

**Issue by eleveni386** [sjdy521/Mojo-Weixin#68]
不增加这个功能, 将ircserver暴露在公网上相当危险, 因为irc本身特性要求开放, 但是我们用来跑微信的话, 又要求私隐, 因为我们这个特殊利用方式. 我觉得还是可以将ircserver私有掉的.

**Comment by sjdy521** [comment]
密码验证是一方面，irc协议是纯文本的，也很容易抓包监听，还需要考虑输出传输采用ssl加密

**Comment by eleveni386** [comment]
@sjdy521 是的讷, 所以 又要辛苦你了.

**Comment by sjdy521** [comment]
已支持密码验证功能，ssl的功能因为本身使用的Mojo框架就支持ssl socket，但可能设计到有效ssl证书的问题，等我先研究下如何配置

需要使用github最新代码，并且升级Mojo::IRC::Server::Chinese 模块到1.8.0版本
开启密码验证的方法参考github文档
https://github.com/sjdy521/Mojo-Weixin/blob/master/doc/Weixin.pod#mojoweixinpluginircshell

```
$client->load("IRCShell",data=>{
        auth => sub{
            my($nick,$user,$pass) = @_; #传递给验证函数的三个参数依次是 irc客户端的NICK/USER/PASS
            if($nick eq '小灰'){#对于昵称"小灰"进行密码验证
                return 0 if not defined $pass; #没有设置密码，验证失败
                return 0 if $pass ne '123456'; #设置的密码不是 "123456" 验证失败
                return 1; #验证成功，允许正常登录
            }
            else{return 1;}#对其他登录昵称不进行验证，全部允许登录
        }
    });
```

**Comment by sjdy521** [comment]
ssl加密传输已支持，详见插件文档介绍
