### ISSUE TITLE
微信几个小时就要重新扫码

### ISSUE THREAD

**Issue by xydche** [sjdy521/Mojo-Weixin#69]
![screenshot_20170211-122551](https://cloud.githubusercontent.com/assets/14014356/22851272/47806bee-efe2-11e6-9557-a308dfe3c651.png)
![screenshot_20170209-094404](https://cloud.githubusercontent.com/assets/14014356/22851273/47834404-efe2-11e6-9e72-ae1ea8b000dc.png)
经常是这两个错误，不知道什么原因

**Comment by sjdy521** [comment]
从日志来看只能确认到是程序运行过程中服务端强制客户端下线的
具体原因无非确认，可能是：
1 你手机的微信点击了退出网页登录？
2 你手机端微信没有保持在线，退出了（程序基于网页版微信，但要保持在线也必须手机端微信也保持在线）

**Comment by xydche** [comment]
谢谢回复。
那有可能是情况2，微信被绿色守护和阻止运行给优化掉了。但是有时候基本没关过微信也掉，有时候关了好几个小时也不掉
