### ISSUE TITLE
plugin.pm 中$module 好像没有预先定义

### ISSUE THREAD

**Issue by autodataming** [sjdy521/Mojo-Weixin#7]
$module = $module_name;
if(substr($module_name,0,1) eq '+'){
            substr($module_name,0,1) = "";
            $module = $module_name;
        }

为什么要考虑 module的名字带有+ 号？

**Comment by sjdy521** [comment]
$module问题已修复

```$client->load("AAA");```
加载Mojo::Weixin::Plugin::AAA包中的call函数（AAA是相对包名）

```$client->load("+AAA");```
加载AAA包中的call函数（AAA是绝对包名）
