### ISSUE TITLE
建议Openwx插件可以增加重新登录API

### ISSUE THREAD

**Issue by qshujun** [sjdy521/Mojo-Weixin#70]
感谢提供这么好的产品，可以让我们小白把微信玩得这么有乐趣，我这里为安全起见将客户端运行在内网、且未将SSH暴露到公网，用python-flask写个简易ApiGateway对Openwx的必要的API代理到公网，以增加token认证和流控。但是使用的这段时间总被客户端被强制下线困扰，原因大致有微信app长时间离线（工作地方网络不好、手机没电等）、客户端机器离线（电信拨号上网，有时会掉线）
     建议客户端控制相关API增加重新登录接口，若APP上点击了退出网页登录、进程被杀或网络原因离线导致客户端被下线，可以通过该接口重新登录，并将二维码发送邮箱或上传图床并返回url，这样就可以远程重新登录了，而不必远程登录机器重新执行脚本。

**Comment by sjdy521** [comment]
这种情况下你可以需要使用提供的多账号管理Controller-API就能满足需要
https://github.com/sjdy521/Mojo-Weixin/blob/master/Controller-API.md

因为多账号管理API采用了master+worker的父子进程模式，父进程会一直运行，提供对外统一的api
也提供客户端启动、停止、状态查询等丰富的api

**Comment by qshujun** [comment]
@sjdy521，非常感谢。

**Comment by sjdy521** [comment]
有几点再补充下
二维码发送到邮件 目前有自带一个插件： PostQRcode

二维码上传到图床获取url地址
目前有一个自带插件 UploadQRcode

加载了该插件 客户端二维码事件上报里也会携带二维码图床url

部署在内网的话 建议多利用下当前提供的事件上报机制
