### ISSUE TITLE
微信confirming状态bug

### ISSUE THREAD

**Issue by yixtan** [sjdy521/Mojo-Weixin#73]
使用 Controller-API 生成一个新的客户端，用手机微信扫描二维码，客户端状态变为 confirming，但故意不在手机上确认登录，超时生成新的二维码后，状态一直停留在 confirming 而不会变成 scaning，直到客户端自动销毁。

**Comment by sjdy521** [comment]
感谢反馈 确实没有去考虑过这种“故意”的情况下程序会出什么幺蛾子，我自己先研究下

**Comment by sjdy521** [comment]
已修复
