### ISSUE TITLE
经常登陆不了

### ISSUE THREAD

**Issue by hdxg4ifh** [sjdy521/Mojo-Weixin#75]
经常手机扫码后，在updating状态又变成scanning状态

**Comment by hdxg4ifh** [comment]
[17/02/28 07:47:56] [error] 更新群组信息失败
[17/02/28 07:47:56] [info] 客户端正在注销...
  -- Blocking request (https://wx2.qq.com/?&lang=zh_CN)
  -- Client >>> Server (https://wx2.qq.com/?&lang=zh_CN)

**Comment by sjdy521** [comment]
当前程序存在这样一个顽固的bug，暂时还没有找到原因解决，会导致需要扫码多次才能够成功
