### ISSUE TITLE
登录的时候二维码无法自动弹出

### ISSUE THREAD

**Issue by yanrs17** [sjdy521/Mojo-Weixin#79]
每次开启显示”等待手机微信扫描二维码...”的时候，二维码无法自动弹出，每次都得手动去/temp/找二维码打开，非常麻烦，希望可以自动弹出，扫完之后自动关闭。

**Comment by csrgxtu** [comment]
弹出可以做，但貌似比较繁杂，需要兼顾各种操作系统的具体环境。

**Comment by yanrs17** [comment]
我还以为是个bug，原来没有做，那就没关系了。

**Comment by csrgxtu** [comment]
请你先在temp目录下扫描，我去调查一下实现这个功能需要的东西。

**Comment by yanrs17** [comment]
感觉放在桌面也比放在temp要好，temp的位置好难找。

**Comment by csrgxtu** [comment]
恩，我一直在使用，然后temp下面有好几百个文件，之前也是一直忍受过来了。

**Comment by csrgxtu** [comment]
http://oylenshpeegul.typepad.com/blog/2012/01/reading-qr-codes-in-perl.html
https://metacpan.org/pod/Term::QRCode
Get qr code image -> extract the info in it -> display it in terminal

**Comment by sjdy521** [comment]
如果是win系统 可以试试UploadQRcode插件 和  ShowQRcode 插件

**Comment by bollwarm** [comment]
temp目录可以设置的的,下面给出一个，启动脚本吧


#!/usr/bin/env perl

use Mojo::Weixin;
my ($host,$port,$post_api);

        $host = "127.0.0.1"; #发送消息接口监听地址，没有特殊需要请不要修改
        $port = 35000;      #发送消息接口监听端口，修改为自己希望监听的端口
        #$post_api = 'http://xxxx';  #接收到的消息上报接口，如果不需要接收消息上报，可以删除或注释此行
        use POSIX;
        my $date=strftime("%Y%m%d",localtime());
        my $client = Mojo::Weixin->new(

           log_level=>"info",
           http_debug=>0,
           log_console=>1,#默认开启
           log_path=>"msg/wxmsg-$date", #现在启动文件夹下新建目录msg:mkdir msg
           tmpdir=>"cookie",          #程序使用的临时目录，主要用于保存一些验证码、二维码等数据，默认为系统临时目录,mkdir cookie
                           #登录cookie的保存文件，默认为 tmpdir/mojo_weixin_cookie_default.dat（多账号运行时设置不同account）
           media_dir=>"media",       #图片接收默认地址，默认为 tmpdir 参数所设置的目录 mkdir media
           download_media=>1,  #是否自动下载媒体文件，默认值为1

            );


        $client->load("ShowMsg");
        $client->load("Openwx",data=>{listen=>[{host=>$host,port=>$port}], post_api=>$post_api});

## 下面是加载邮件传送二维码路径

$client->load("PostQRcode",data=>{
    smtp    =>  'smtp.163.com', #邮箱的smtp地址
    port    =>  '25', #smtp服务器端口，默认25
    from    =>  'xxx@163.com', #发件人
    to      =>  'xx@ijz.me', #收件人
    user    =>  'xxx@163.com', #smtp登录帐号
    pass    =>  'ooxxx123$#@!',
    tls     =>  0,      #可选，是否使用SMTPS协议，默认为0
                        #在没有设置的情况下，如果使用的端口为465，则该选项会自动被设置为1
});

$client->run();
