### ISSUE TITLE
群发送消息时如何设置@功能

### ISSUE THREAD

**Issue by lzf0112** [sjdy521/Mojo-Weixin#80]
RT，在群里怎么@其他人呢？ 

@displayname 好像没效果。

**Comment by bollwarm** [comment]
这个腾讯web端不支持，所以工具也不支持

**Comment by tossp** [comment]
`@`的后面不是空格是一个特别符号`\u2005`
用`@\u2005用户昵称`的格式就可以了

**Comment by sjdy521** [comment]
@tossp 确认这样可以？一般来说是不可能的

**Comment by tossp** [comment]
@sjdy521 我试过，`记得`结论是可以，，，囧，，，
逻辑上是说得通的，毕竟给信息发送给wx服务器的字段没有专门标识at了谁的字段，这个被at的提醒应该是客户端自己判断的本地逻辑
这里有个小坑，群友同时是好友，必须用好友的NickName，而不能用GroupNickName，，，记得是。。。。

**Comment by sjdy521** [comment]
测试了一下 没用效果

**Comment by eatmoreapple** [comment]
> @sjdy521 我试过，`记得`结论是可以，，，囧，，， 逻辑上是说得通的，毕竟给信息发送给wx服务器的字段没有专门标识at了谁的字段，这个被at的提醒应该是客户端自己判断的本地逻辑 这里有个小坑，群友同时是好友，必须用好友的NickName，而不能用GroupNickName，，，记得是。。。。
> 
> BTW，上面的代码片段是我用golang写的

hello，你确定可以吗？我试验了你的写法，但是不起作用
