### ISSUE TITLE
发送图片经常失败，但是登录WEB版是可以发的

### ISSUE THREAD

**Issue by lijibiao** [sjdy521/Mojo-Weixin#82]
改用media_upload了，能返回media_id，但是发送消息的时候，依然出错
{"code":-1,"id":1489029181210,"media_id":"","status":"unknown error"}

登录WEB版是可以发的，感觉应该和腾讯没多大关系

**Comment by sjdy521** [comment]
使用的是最新版本吗

**Comment by lijibiao** [comment]
检查了下，可能是我对media_id做了缓存处理导致的，因为有一张图要发多次，我就缓存了下。去掉了后目前还比较稳定

**Comment by sjdy521** [comment]
media_id发送多次按理说应该没问题吧

**Comment by lijibiao** [comment]
现在看返回1205的code码，不知道什么意思，还是图片发送不成功
{"code":1205,"id":1489039261544,"media_id":"","status":"unknown error"}

**Comment by lijibiao** [comment]
@sjdy521 使用的是最新版的

**Comment by sjdy521** [comment]
可以这样开启debug模式`Mojo::Weixin->new(http_debug=>1,log_debug=>1)` 把发送media_id错误的上下文日志发给我看下
