### ISSUE TITLE
找寻群组如何使用 正则表达式？

### ISSUE THREAD

**Issue by yanrs17** [sjdy521/Mojo-Weixin#84]
因为有的时候不一定能找到完全对应的，
比如我有各种各样的Perl群，群名都包含Perl，但名字都不一样，比如“Perl一群"，"Perl二群"，等等，尝试直接用search_group(name=>"Perl")找不到这些群，必须要输入全名(name=>"Perl一群")才能找到，不知道可不可以用正则表达式，可以的话怎么用，或者是否有不是完全匹配的search_group，就是那种只需要输入一部分文字，就能找到里面含有这些文字的 所有 的群
```
my $group = $client->search_group(name=>xxx);
```
好友同
```
my $friend = $client->search_friend(name=>xxx,id=>xxx,);
my @friends = $client->search_friend(city=>"北京");
```
谢谢～

**Comment by lijibiao** [comment]
接口应该是不支持，可以遍历全量群，再通过正则匹配

**Comment by yanrs17** [comment]
那有什么办法找到自己的所有群呢

**Comment by lijibiao** [comment]
get_group_info

**Comment by yanrs17** [comment]
这个貌似要用到openwx，有不用这个的方法吗

**Comment by sjdy521** [comment]
你要基于自己写perl代码来做这个事情吗，还是走Openwx的http接口

**Comment by yanrs17** [comment]
我想做一个群主管理，我是很多群的群主，每天都有很多人来问我有没有这个那个的群，一个个邀请好烦，想要就是说这个账号如果接到好友私聊的命令，比如"群 Perl”，第一个"群"是指令，后面的Perl是有关的群，就会把所有的带有"Perl“的群邀请自动发给这个好友，其他部分写得差不多了，就差这个查找群了。
想自己用Perl边学边写，不知道可不可行。

**Comment by sjdy521** [comment]
基于perl来写的话就很灵活了，你可以不使用我提供的search_group函数，而是自己遍历所有的群名称，然后自己模糊匹配想要的群，参考代码：

```
my $match_keyword= quotemeta("Perl");  #对输入的匹配关键字进行quotemeta处理，正则元字符被转义
for my $group ($client->groups){
    next if $group->displayname !~/$match_keyword/i; # 模糊匹配群名称中包含perl的关键字，并忽略大小写，不匹配就跳过
    print "匹配到的群：" . $group->displayname . "\n";
}
```

**Comment by yanrs17** [comment]
可以用了謝謝
